### ISSUE TITLE
Create a routine that updates the ECV nightly

### ISSUE THREAD

**Issue by richardbank** [Signbank/NGT-signbank#101]
The ECV on /www/signbank/live/writable/ecv/ is now updated only when the button on the search page is clicked (see #19). Create a routine that also does this automatically every night.

**Comment by henrinie** [comment]
Is this issue about an externally controlled vocabulary for ELAN?

If it is, have you considered just making an url for signbank where you can always get the up to date ECV? If you have some reasons why this is not a good idea, I would like to hear about them. I have no experience with ELAN myself, so all information considering this would be helpful.

**Comment by ocrasborn** [comment]
Hi Henri: the ECV is indeed what ELAN can link to (in its specification of a Linguistic Type). It consists of information from Signbank, that is exported to an xml file on a URL that is then entered in each ELAN file. (Actually, it's not directly specified for the linguistic type, but first as the location for a Controlled Vocabulary; this CV has a name, and that is what Linguistic Types can refer to.)

**Comment by Woseseltops** [comment]
Note to self: I started with this with a curl command in my crontab, but it seems to fail because cron is not logged in.

> If it is, have you considered just making an url for signbank where you can always get the up to date ECV?
 
Good point, I'm not fully sure why we decided this way. What we now have is request A, which generates the (updated version of the) file and saves it, and request B, which returns this saved result. What you're proposing is to merge these two requests into a single request C, so that you have only one request that always updates the file and returns the results. An advantage of the current approach could be that the response to request B is much faster, which might save ELAN users some time.

**Comment by Woseseltops** [comment]
I created a separate url http://signbank.science.ru.nl/dictionary/update_ecv/ that can be accessed without an account. Cron visits this address every night at 2:30h . 

To do:
* Verify that it works
* Move the cron command to Onno's account.

**Comment by henrinie** [comment]
@Woseseltops You are right about it taking more time than a single request. It would be interesting to know how much time it takes. I tested it with our production server, but we have only 95 glosses in there. It took 84ms total to receive the xml file, 63ms was for waiting and 9ms for receiving the xml.
It would be interesting to know how it would work with 10k Glosses for example, but I don't really want to test it with our production server, and I don't have other means of getting realistic feedback about that.

**Comment by Woseseltops** [comment]
@henrinie , to give you an idea: for our 3233 glosses, updating the ECV takes 14.68 seconds, en requesting it took 98ms.

**Comment by ocrasborn** [comment]
It works.
Does the cron command still need to be moved to my account (cf. comment above)?

**Comment by Woseseltops** [comment]
Yes. I just did that, and commented it out on my accounts. Please leave this issue open so I don't forget to check whether it works.

**Comment by ocrasborn** [comment]
[See my mails on the log mails I get every morning] Plus: can we alter this from a mail message to writing  incrementally to a log file that rotates every month, or something like that?

**Comment by Woseseltops** [comment]
Info from Onno's mail:

**Comment by Woseseltops** [comment]
Most importantly, I checked this, in it works. A new ECV file was created this night at 2:30h, and since this is exactly the time that I put in Onno's cron file (and removed from my own), this can only mean Onno's account on Ponyland now pushes the ECV button automatically every night :).

As for the weird output, I looked it up and it seems to be part of curl, the command that does the button pushing. @ocrasborn , I can try to supress the output if you want?

**Comment by ocrasborn** [comment]
@Woseseltops, If you think the log info is worth keeping, please move this one too to a (rotating) log file, rather than a daily mail message to me.

**Comment by Woseseltops** [comment]
The mail thing is crontab default behavior; I've now changed it so it writes output to a file in /scratch/signbank-logs/ . 

Next up:
* Adding a cron task that deletes files older than a week.

**Comment by ocrasborn** [comment]
I still get email logs. This morning's one said this (exactly the same as the 'svn update' output):

/bin/sh: 1: Syntax error: EOF in backquote substitution

**Comment by Woseseltops** [comment]
I looked it up, and it turns out that cron cannot handle the % sign, which was in the part that creates the daily log file... and of course it emailed you about it because it didn't know what to do with the error. I've fixed it now, let's see what the next problem will be.

PS
It is normal that it takes a lot of time to get a cronjob right ;).

**Comment by Woseseltops** [comment]
@ocrasborn , do you still get emails?

**Comment by ocrasborn** [comment]
@Woseseltops: No, I don't.

**Comment by Woseseltops** [comment]
Weird, because it still does not fully work; it creates the logfiles, but it does not write to do them. I've slightly altered the commands now.

**Comment by Woseseltops** [comment]
I now see log files with expected content. It works?

**Comment by ocrasborn** [comment]
Works!
