### ISSUE TITLE
Change display of links to morphemes and related signs

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#120]
In the tables of the panels Morphology and Relations to other signs, users can jump to the related element by clicking on "(view)". I thought we had already altered that, but can't find it back in the issues: please put the link on the morpheme/gloss itself, removing the "(view)" altogether.

Screenshots for illustration:
![screenshot 2016-01-21 17 33 47](https://cloud.githubusercontent.com/assets/10242207/12473305/32e4caca-c065-11e5-8617-1e7d4e2b8237.png)
![screenshot 2016-01-21 17 33 16](https://cloud.githubusercontent.com/assets/10242207/12473307/3473e77c-c065-11e5-86c4-201eadcd2b57.png)

**Comment by ErwinKomen** [comment]
Actions:
- Adapted the morpheme_detail.html so that the "Appears in" list now does not contain (view), but the links immediately on the glosses
- Did the same in gloss_detail.html for all similar lists there (related to morphemes and compound-components)
- Same in gloss_detail.html and morpheme_detail.html for the relation to other signs list

@ocrasborn : that should cover them all. Okay now?

**Comment by ErwinKomen** [comment]
One remaining and related issue: the list of signs (glosses) in which a component (which also is a gloss) is used must be *read only*, since such a list is _derived_ from those signs that specify which components are part of it. 
Current behaviour: selecting an item from the list leads to opening of an editor
Desired behaviour: link through to the indicated sign (=gloss)

**Comment by ErwinKomen** [comment]
Solved: removed the 'edit-sensitive' CSS class names from the items in this list in gloss_detail.html

**Comment by ErwinKomen** [comment]
@ocrasborn : solved satisfactorily?
