### ISSUE TITLE
Enforce consistency for Language/Dialect pairs

### ISSUE THREAD

**Issue by richardbank** [Signbank/NGT-signbank#123]
Language and Dialect are two fields that, once chosen, are compulsory (not when adding signs, though, only when you edit the Language or Dialect field). Moreover, it is inconsistent:
- it is possible to choose Language NGT with Dialect Shanghai, for instance; make it so that each Language can only have the Dialects specified for that language - [see here](http://signbank.science.ru.nl/admin/dictionary/dialect/)
- choosing Dialect Unknown results in following the somewhat funny error:
  ![image](https://cloud.githubusercontent.com/assets/10399929/12850471/2363cb48-cc25-11e5-8cec-4ca4493982a7.png)

Please make Unknown possible.

**Comment by henrinie** [comment]
I am considering changing the Language part of Signbank in FinSL SB. See: https://github.com/Signbank/FinSL-signbank/issues/129

I am planning (until I change the plans) to have Datasets ("one instance of a dictionary") that have one Language set to it, instead of setting language to every Gloss itself. Then it should be possible to select only Dialects of the selected Language for all the glosses in a Dataset.

**Comment by susanodd** [comment]
This has been fixed. (Issue #133.)
The Dialect choices in Gloss Detail View are now prefixed with the Sign Language and it's checked that the Dialect is for the Gloss's sign language.
The (current) Unknown choices are now unambiguous: CSL/Unknown or NGT/Unknown.

(Avoid testing out absurd combinations you don't really want. If you need to set a Sign Language or Dialect back to None, this needs to be done in the Admin pages.)

**Comment by susanodd** [comment]
Here are some screenshots.
The first two show that you can set an Unkown dialect for the NGT sign language.
The third one has done something weird and changed the sign language to Kata Kolok after setting the dialect to NGT/Unknown.
There aren't any dialects for the Kata Kolok language, but the dialect can't be changed to empty.
(I assume that users know what they're doing and don't do this. Otherwise, there would need to be Unknown dialects for all languages without any dialects. Or a way to set this to empty.)

![dialects-gloss-view](https://user-images.githubusercontent.com/24272544/32550617-16dc10de-c48e-11e7-9fe9-f8cfae13fe5d.png)
![dialects-gloss-view-select-unknown](https://user-images.githubusercontent.com/24272544/32550621-1b942ce2-c48e-11e7-9c04-871c5fa9e50e.png)
![dialects-gloss-view-weird](https://user-images.githubusercontent.com/24272544/32550625-1f9bbabc-c48e-11e7-89f0-f2dadf3fe160.png)

**Comment by susanodd** [comment]
When updating the Dialect, if no Language has ben set, then the Language of the newly chosen Dialect is used.
I could make it so that if you already have a Dialect chosen (for your Language), that if you want to set your language again to something totally different, that the Dialect is made empty if it doesn't match the new language.
@ocrasborn any preference?

**Comment by ocrasborn** [comment]
I think the former would be better, @susanodd

**Comment by susanodd** [comment]
@ocrasborn, is this okay: when resetting the Language field to a different Language that doesn't match the (current) Dialect anymore, then reset the Dialect to empty? Is that okay?

**Comment by ocrasborn** [comment]
Yes, that's OK.

**Comment by susanodd** [comment]
Okay, this has been fixed. Pushed to github.
