### ISSUE TITLE
RU-logo and NGT Signbank-header have disappeared from view

### ISSUE THREAD

**Issue by richardbank** [Signbank/NGT-signbank#126]
Please repair :-)

**Comment by Woseseltops** [comment]
They're back. The solution turned out to be that I had moved the images directory for #114. I thought I also changed all references, but apparently I missed some references in the css file.

The problem was made extra confusing by (1) the fact that images and css files are often cached, so the problem did not show up until long after the move of the images and (2) the fact that apparently it is not shown in Chrome's debug window when images that are loaded via a css are not available.
