### ISSUE TITLE
Move Language/dialect fields

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#133]
* The Language/Dialect fields are now in a bit of an odd place in the detail view. Where could we better move them?
* Consideration: when there are data from multiple sign languages in a single database, we will need a filter to select which language's data to show. When we think of a good way to do that, displaying 'language' as a field (in the detail view) is a bit redundant in that case -- but not if searches across multiple languages are carried out.
* The dialect field could be displayed somewhere in connection with the language filter, or move to a less hidden-yet-space-consuming place than a panel.

**Comment by richardbank** [comment]
Would be good to combine this with #123.

**Comment by Woseseltops** [comment]
This issue was created before the introduction of datasets, so I find a difficult to translate the written request to the underlying wish (which apparently is still there, given that this got high priority in November). Is it the underlying wish: get rid of the 'Language & dialect' panel?

If yes, let me define a few terms before continuing:
* Sign language
* Translation language (language of the gloss used to describe the sign language)
* Interface language

The panel 'Language & dialect' is about the first option, and contains three fields: language, dialect and dataset:
* I feel the dataset field would also fit in the 'Publication status' panel, as this panel contains all information on things which are not inherent to the gloss, but are more related to its place within Signbank. 
* The language field, on the other hand, is about the sign language and so is inherent to the gloss, which makes it less suitable for the 'Publication status' panel. However, sign language follows from the dataset field: a dataset can only have one sign language. For that reason, I see no problem putting it behind the dataset between parentheses instead of in a separate row.
* That leaves us with the dialect field, which is rarely filled. Maybe move it to the main attributes (which are on top, not in a panel), but only show it when it is filled?

Let me know what you think, @ocrasborn , and if I even understood the issue correctly.

**Comment by ocrasborn** [comment]
Let me discuss with our American and Norwegian colleagues what to do with dialect. Sign language has become superfluous now (predictable from dataset), could simply be deleted if we could search for 'the sign language (of a gloss of a dataset)'.
That said, we do still need a better way of visualising the dataset property with glosses, I'll make new issues for that.

**Comment by Woseseltops** [comment]
Okay, so:
* Instructions on what to do with dialect will follow later
* For the language/dataset stuff separate issues are created

Okay to rename this issue: 'Move dialect field' and remove the high priority tag?

**Comment by ocrasborn** [comment]
Let's keep the high priority tag and finish it off: please move the dialect field to the top of the detail view, above the lemma id gloss.
The panel where it is now can then be removed.

**Comment by Woseseltops** [comment]
Okay done, and moved dataset to publication data. 

Do you also want to hide the dialect field when it is empty?

**Comment by ocrasborn** [comment]
* Yes, please, hide it when empty.
* Move it to the top, above Lemma ID gloss

**Comment by Woseseltops** [comment]
* Took me some time to figure this out (you can select multiple dialects, so I couldn't reuse the code from the phonology fields), but done!
* Done

Accidently gave Git commit 8648187 the wrong issue nr
