### ISSUE TITLE
Add ASL-specific fields

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#136]
See excel overview

**Comment by Woseseltops** [comment]
Done:
* The new ASL-fields are now there in the code.
* The ASL-database knows about them.
* Deactivated the Dutch-only fields in the settings file.

Notes:
* I assumed all fields that are not related to phonology, semantics or frequencies were universal, so you cannot influence them from the settings file. In retrospect, this is of course not true for 'annotation_id_english', which is Dutch only, so I have to come up with an elegant solution to include that in the settings file as well.
* I think the Americans will want to change some names of fields (for example 'Thematic category' instead of 'Semantic field'). We will also need some setting for that as well.

For both ideas goes: not sure if I have an acceptable solution before your demo, @ocrasborn .

**Comment by Woseseltops** [comment]
Made a spin-off issue #151

**Comment by Woseseltops** [comment]
Yeah! I finally got the American-English language working on http://applejack.science.ru.nl/asl-signbank . Next up: fix all the stuff with the titles not showing.

**Comment by Woseseltops** [comment]
I think all that needs to be done is to add translations where the Americans want them; shall I do already what I kwow, or do we let them it themselves?

**Comment by ocrasborn** [comment]
Please go ahead and change what you can, then I will check with them what remains.

**Comment by Woseseltops** [comment]
Done. I thought this would be a huge task, but in the end I only changed 5 or so labels on the basis of the American fields excel file you once sent me!
