### ISSUE TITLE
Make search results sortable by clicking on table header

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#143]

**Comment by henrinie** [comment]
This can be done with https://docs.djangoproject.com/en/1.9/ref/models/querysets/#django.db.models.query.QuerySet.order_by 

Another possibility is to use a 3rd party app like https://github.com/bradleyayers/django-tables2
Which makes the process easy, but you would also be relying on that piece of software, and that it will be maintained in the future.

Fields like translation equivalents are pretty hard to sort because they have multiple values, so the order would not mean anything really.

**Comment by ErwinKomen** [comment]
Columns are now as far as possible sortable alphabetically.
Only **one** column can be sorted ascending or descending at a time.
The sorted column has a red-colored triangle.
Undoing the sort is done by pressing the 'x' sign of the sorted column.
