### ISSUE TITLE
Allow for uploading image files in Other Videos panel

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#146]
= extension to #145 

* Rename panel "Other Videos" to "Other media"
* Allow for adding image files in the same way as video files, with the same options (Video/image -- Type -- Alternative gloss)

**Comment by Woseseltops** [comment]
Renaming the thing in the html was easy enough, but I decided it would be cleaner to also fix it in all variable names etc everywhere. Pfff that was long and errorprone work - see the last commit if you want to feel my pain :). 

Not done yet: renaming the actual model, because that's more complicated http://stackoverflow.com/questions/2862979/easiest-way-to-rename-a-model-using-django-south

**Comment by ocrasborn** [comment]
<looked> Ouch!

**Comment by Woseseltops** [comment]
Done!
