### ISSUE TITLE
Allow batch uploading of 'Other videos'

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#156]
* See also #20 
* Here, batch upload should not just match file names to glosses, but also allow import of alternate glosses. By way of an optional CSV file that lists alternate gloss and the type of alternate video?

**Comment by Woseseltops** [comment]
Done, in a first very basic version after some discussion with @richardbank . To make it work, you should:
* Upload a number of videos to /www/signbank/live/writable/import_other_videos/ 
* Add a file named index.csv with this format (example)

```
Idgloss,filename,type,alternative_gloss
wesseltest3,test1.mp4,"Sign in sentence context","some text"
wesseltest3,test2.mp4,"SignPhon: sentence","some text"
```

* Visit http://signbank.science.ru.nl/dictionary/import_other_videos/

Because some many things can go wrong, I would like to add good error handling, so not done yet... and possibly @ocrasborn wants to change some things on how this works exactly?

**Comment by Woseseltops** [comment]
Done; error message handling added

**Comment by Woseseltops** [comment]
Is now called http://signbank.science.ru.nl/dictionary/import_other_media/ because of #146

**Comment by Woseseltops** [comment]
Can this be closed?

**Comment by ocrasborn** [comment]
I have yet to test it, but let's close it for now.
