### ISSUE TITLE
Change colouring of search hits

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#159]
Op dit moment zijn in de search results alle hits groen als er een video voor geüpload is. Dat was handig omdat we niet vele video’s hadden in het begin. Inmiddels is de situatie omgedraaid: we zijn bijna klaar met filmen. Zou je daarom alle hits die geen video hebben rood kunnen maken?

Eigenlijk hebben we nog twee categorieën waarvan het ook goed zou zijn als we die visueel zouden highlighten:
- Gebaren met de checkmark ‘Proposed new sign’ hebben meestal wel een video, maar een tijdelijke video die met de webcam is opgenomen.
- Gebaren met een foute video (meestal: het foute gebaar) hebben de tag ‘Video: wrong sign’

Het mooist zou eigenlijk zijn als we die visueel iconisch markeren: van minder erg naar Pas Op! Met het volgende stoplichtsysteem:

Wrong sign: rood
Geen video: oranje
Proposed new sign: groen

En dan niet al te knal, maar wat lichters/half-transparants/pastellerigs.

**Comment by ErwinKomen** [comment]
![issue159](https://cloud.githubusercontent.com/assets/11887269/15540963/54e5fc5c-228a-11e6-9162-53ab50f9b8ab.jpg)

The color scheme that is most convenient makes use of Bootstrap's built-in classes:
wrong sign: bootstrap 'danger' >> color is salmon
video missing: bootstrap 'warning' >> color is yellow
new sign: bootstrap 'info' >> color is blue

Is that acceptable (see picture)?

**Comment by ocrasborn** [comment]
Yes, it is.

**Comment by ErwinKomen** [comment]
SELF: implementation details

1. wrong sign: use new function gloss.is_wrong_sign in dictionary/models.py
   a] This uses new function Gloss.has_tag("video:_wrong_sign")
   b] That uses tagging.models.Tag.objects.get_for_object(self).filter(name=tagname)
2. video missing: use existing {% if not gloss.has_video %} in admin_gloss_list.html
3. new sign: use existing Gloss field [isNew]

**Comment by Woseseltops** [comment]
:+1: for using Bootstrap for the colors

About the architectural question where to do the check for the presence of the 'wrong sign' tag. I see 4 locations:
*  Hardcoded in the Gloss model, as you had it initially. I agree that this is not the best solution, because this tag might not be there on all servers running our NGT-Signbank repo.
* A more generic check for the presence of a tag on Gloss the model. Downside: this is about the presence of a Tag... the model Gloss shouldn't have to worry about it.
* Somewhere in the GlossListView, which is typically where you do these kind of checks. Downside: getting the outcome of the check to the template somehow gets really messy in this particular case, with separate variables and stuff.
* In the template itself (the current solution). Downside: this is not really about the visual side of it all, which is what templates are meant for.

Because I don't know which downside is more important, I suggest to keep as you made it :).

**Comment by ocrasborn** [comment]
I closed this too quickly. Related request, now that it's all still fresh in your mind: please apply the same colouring criteria and scheme to http://signbank.science.ru.nl//signs/recently_added/, where red is now used to mean 'no video present' -- which will confuse users.

**Comment by ErwinKomen** [comment]
Okay, @ocrasborn I have applied the same three-color scheme to 'recently_added'n and committed the changes to github.
It is a bit weird, though, since the background color now defaults to light-blue -- all are in principle 'new'.
But it's consistent...
