### ISSUE TITLE
Decide on Signbank software license

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#160]
See mail discussion with Henri/Steve

**Comment by henrinie** [comment]
Auslan Signbank uses the 3-clause BSD license:
https://en.wikipedia.org/wiki/BSD_licenses

**Comment by Woseseltops** [comment]
I know colleagues @proycon has ideas about software licenses, maybe we can consult him?

**Comment by Woseseltops** [comment]
@ocrasborn , @henrinie  asks us to give this priority. He has proposed a license for FinSL SB over there, maybe we can use it as well? What I say about it in the issue over there:

> In other RU software projects, the vision always is to make everything as open as possible; it was paid for by public money, so the results should be given back to the public. This seems to be what is meant with "THIS SOFTWARE IS PROVIDED [...] AS IS" in the license you propose, so it might be appropriate for us to use as well. On the other hand, 'All rights reserved' seems to imply the opposite.

**Comment by Woseseltops** [comment]
Cleaning up on the issues, and discovered we still haven't decided on this one. I suggest we follow FinSL and use BSD-3. I looked it up, and this license seems to allow anything as long as people mention our name. 

Actually, turns out Github already lists the BSD-3 clause on the homepage of our repo because of the license file that has been there since the days of Steve :). I only added the RU. Close if you agree, @ocrasborn .

By the way, do I understand correctly that this only about the code, and not about the actual data itself? Because in the footer and the license page of Signbank I see a Creative Commons thingy.

**Comment by ocrasborn** [comment]
Indeed, this is only about the code. We should remove the CC from the footer, as these licenses will be dataset-specific from now on. Could you take that up as part of this issue, @Woseseltops ? After that, we can close this.

**Comment by ocrasborn** [comment]
Oops, I cannot edit page fields for NGT signbank, although it's solved for ASL (#279). Is this a temporary thing, or should we re-open #279, @Woseseltops ?

**Comment by Woseseltops** [comment]
> We should remove the CC from the footer, as these licenses will be dataset-specific from now on.

Done.

>  cannot edit page fields for NGT signbank

Fixed (but you already I knew that I see :) )
