### ISSUE TITLE
ASL Signbank keeps reloading (for some users)

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#167]
I never had this problem (user onno), but it keeps the ASL team from actually using Signbank. We create a new user, e.g. dummy (feel free to play around with that one and change the pwd to use it), log out as ourselves then log in with this new user account... voilà, endless reload and impossible to even select a menu item in those milliseconds in between.

**Comment by ocrasborn** [comment]
@ErwinKomen : Might be the same thing as #80

**Comment by Woseseltops** [comment]
This is a language related thingy. It reloads if the interface language does not match what it saved as the 'last used language'. This reloading should switch the interface language, but if this does not work, it keeps reloading.

@ErwinKomen, @ocrasborn maybe I can look at this first, because I've worked on this problem many times before

**Comment by Woseseltops** [comment]
I already know the solution: the language should be en-us, while for new users the language defaults to 'en'. I will now try to add that you can influence this default value.

**Comment by Woseseltops** [comment]
Done.
