### ISSUE TITLE
List of recently added signs doesn't seem to work for ASL

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#169]
I don't see anything when I select the menu item Signs > Recently added signs (page that also shows after logging in), even the test item I just added.

**Comment by Woseseltops** [comment]
After some investigation, I found the reason: as specified in #74, a sign only appears in this list when 'proposed new sign' is checked. Apparently, the Dutch Signbank users all check this box when they add something new, which is why their signs show up in the list. For all American signs, on the other hand, 'proposed new sign' is false, which is why the list is empty. If you change that (I tried it temporarily), the signs shows up immediately.

**Comment by ocrasborn** [comment]
Ah right. I will explain to the ASL users; thanks.
