### ISSUE TITLE
Re-activate the public ("Dictionary") view

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#170]
We'd like to start using the original Dictionary view again that is accessible to anyone without logging in, but for the moment:
- only for NGT, not ASL
- only display (and allow searching for) signs that have the tag "Radboud sign"

**Comment by Woseseltops** [comment]
> start using the original Dictionary view again that is accessible to anyone without logging in

When should you see what? I propose: always the detail view when allowed, otherwise the public view. In the detail view is a button to also see what the public view looks like.

> only for NGT, not ASL

Okay, so this will be a setting in the settings file.

> only display (and allow searching for) signs that have the tag "Radboud sign"

I think we have a field called 'In web dictionary' for this purpose, I propose to use it for this :). Shall I write a script that makes sure everything with the tag Radboud sign is in the web dictionary, and the rest is not? Or do you think we would like to do this more often, and shall I create a feature that allows users to activate and deactivate groups of signs based on their tags?

**Comment by ocrasborn** [comment]
- Proposal on when to see what: agreed.
- Proposal for using web dictionary: of course! Thanks for reminding me. Let's just script the Radboud tag to a checkmark for now, and wait with the other feature, I doubt we'll do this again.

**Comment by Woseseltops** [comment]
Done:
* All glosses are now NOT in the web dictionary, unless they had the tag Radboud sign
* You no longer need any permission to see the public view of sign if it's in the web dictionary. If you're trying to visit the public view of a sign you're not allowed to see (for example because you're logged out and it's not in the web dictionary), the view does not show any data but instead displays the message 'you're not allowed to see this sign'.

Not done yet:
* Normally when you're visiting a page and you're not allowed, you are redirected to the login page when not logged in, or not shown anything when you are. An exception needs to be added to this behavior so that you are redirected to the public view instead when (1) the page was the detail view of a sign and (2) this sign is in the web dictionary.

**Comment by ocrasborn** [comment]
1) I think we still need to allow non-logged in users to search / list signs; how would they find sign entries now?
1b) Searching should only be allowed through the two fields in the menu bar. So not using the list view-with-search-fields.
2) It would be good if non-logged in users were not bothered with entries they cannot see. If someone pastes in a direct link to a detail view of a 'not in dictionary' sign they should see the log in page, but otherwise search results should not refer to any other entry.

**Comment by Woseseltops** [comment]
> I think we still need to allow non-logged in users to search / list signs; how would they find sign entries now? 1b) Searching should only be allowed through the two fields in the menu bar. So not using the list view-with-search-fields.

Aha, so the whole user experience should be accessible, not just the public view :). As far as I can oversee it now, this adds the following items to my to do list:
* Make search available without any permissions.
* Only show the more complicated search options when you have the permissions.
* In the search results, only mention the ones you have permissions to view (that is: if you don't have permission to view detail views, only mention the glosses in the web dictionary).

> If someone pastes in a direct link to a detail view of a 'not in dictionary' sign they should see the log in page

This sentence made me realize I'm a bit confused about what should happen when, and when I'm confused I make tables :). I think this is how we want to do it:

When visiting the URL of a detail view:

||Gloss in web dictionary||Gloss NOT in web dictionary||
|---|---|---|---|---|
||**Permission for detail view**|**No permission for detail view**|**Permission for detail view**|**No permission for detail view**|
|**Logged in**|Show detail view|Redirect to public view|Show detail view|Show nothing|
|**Not logged in**|Redirect to public view|Redirect to public view|Redirect to login|Redirect to login|

When visiting the URL of a public view:

||Gloss in web dictionary||Gloss NOT in web dictionary||
|---|---|---|---|---|
||**Permission for detail view**|**No permission for detail view**|**Permission for detail view**|**No permission for detail view**|
|**Logged in**|Show public view|Show public view|Show public view|Show public view|
|**Not logged in**|Show public view|Show public view|Redirect to login|Redirect to login|

**Comment by Woseseltops** [comment]
Done:
* Some changes to the second table
* Made the redirects work as in the table.

**Comment by henrinie** [comment]
@Woseseltops your tables are awesome! It is so easy for everyone to understand the issue completely very fast. Keep up the good work. :+1:

**Comment by Woseseltops** [comment]
Changes:
* The search page is available without having to log in
* The 'form your query' panel is only available if you have the rights, otherwise you don't see it
* If you don't have enough rights, there will be an extra (invisible) search filter that filters out all signs not in the web dictionary

To do:
* I just noticed that you still get permission problems when using the search fields in the menu bar
* The 'total number of signs' mentioned on the page is still the overall total number... maybe we want to display the total number of signs *that are available to you* ?

**Comment by Woseseltops** [comment]
Also fixed: 'I just noticed that you still get permission problems when using the search fields in the menu bar'

**Comment by Woseseltops** [comment]
So this question is open for @ocrasborn : The 'total number of signs' mentioned on the page is still the overall total number... maybe we want to display the total number of signs that are available to you ?

**Comment by ocrasborn** [comment]
Yes, that would be good. So that would mean 'all sign entries' for users that are logged in, and 'all signs that have the In Dictionary checkmark' for users that are not logged in. At least for now: we will need to revise this when we start distinguishing multiple datasets for different languages, see e.g. #223 
(part of https://github.com/Signbank/NGT-signbank/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Multiple+Languages+%2F+Datasets%22)

**Comment by ocrasborn** [comment]
See mail from @vanlummelhuizen : the present version of the code also restricted the access for users that were logged in, so he reverted to an older version of the code earlier this week.

**Comment by Woseseltops** [comment]
Already fixed that yesterday morning (see commit #9631d7b), but forgot to let anyone know about it :)

**Comment by Woseseltops** [comment]
Done @ocrasborn ?
