### ISSUE TITLE
Make all Signbank data available in ELAN by making it downloadable in packages

### ISSUE THREAD

**Issue by vanlummelhuizen** [Signbank/NGT-signbank#186]
(translated from an email sent earlier)

The connection between Signbank and ELAN will be made by putting all Signbank data into a package (e.g. zipped) that can be downloaded by ELAN through a webservice API. The package contains all glosses and of each gloss 
1. all data fields
2. all media (images, videos etc.) in small format (how small? how to shrink? (with ffmpeg/avconv))

ELAN uses this package as a kind of ECV+, so when showing, creating/editing of annotations, in the lexicon tab or showing the gloss video in several places.

A package has a certain timestamp and the API makes it possible to download only the changes between 2 timestamps (normally the timestamp of the last downloaded package and now). ELAN will ask for a new package at strategic times, strategic for the ELAN user that is.

The reason to have all Signbank data saved locally is that CNGT computers are already fit for large amount of data. It also helps to show the gloss videos if they are stored locally.

Tasks/questions for the Signbank team:
- How does the API work? How to sign in?
- What does a package look like?

Tasks/questions for the ELAN team:
- How to store the Signbank data?
- How to use the Signbank data in ELAN?
- How does the link back to Signbank work? Through a web link in the default browser.

**Comment by vanlummelhuizen** [comment]
@ocrasborn There are a few possibilities for making the link to Signbank in ELAN:

1. Leave the ECV-link as it is and make ELAN notice it is actually a Signbank-ECV (either by finding 'signbank' in the link, the ECV giving some hints or just plain probing). When ELAN determines it is dealing with a Signbank, some magic happes. The user only notices something being downloaded. A lot the first time, some smaller packages later on.
2. The user explicitly makes a Signbank-link in ELAN. ELAN may then notice the link is similar to a ECV-link, after which the above describe magic happens.
3. The user explicitly makes a Signbank-link AND make an ECV refer to that Signbank link.

**Comment by Woseseltops** [comment]
> What does a package look like?

A first draft:

Going to `signbank.science.ru.nl\package` would result in

```
Signbank_package.123456.zip
* glosses.json
* videos/
  * AA
    * AANBELLEN-752.mp4
    * AANBIEDEN-2439.mp4
    [...]
  * AB
    * ABONNEMENT-3174.mp4  
    * ABORTUS-A-813.mp4
    [...]
  [...]
* images/
  * AA
    * AANBELLEN-752.png
    * AANBIEDEN-2439.png
    [...]
  * AB
    * ABONNEMENT-3174.png  
    * ABORTUS-A-813.png
    [...]
  [...]
```

Note that any media from the OtherMedia folder (basically a function to store any files related to a gloss) are not represented... are they needed for Elan? 

I imagine patches would be created by adding an argument `signbanks.science.ru.nl\package?from_timestamp=12345`, and would be looking like this:

```
Signbank_patch.12345-34567.zip
* glosses.json
* videos/
* images/
* deleted_glosses.txt
* deleted_videos.txt
* deleted_images.txt
```

All glosses present in glosses.json indicate either changed or newly created glosses, and the same goes for the files in videos and images. When something occurs in deleted_*.txt, which is simply a linebreak-separated list of personal keys (for glosses) or filenames (for videos and images), this indicates this item has been removed.

**Comment by vanlummelhuizen** [comment]
@Woseseltops This looks promising. Two related questions so far: how are glosses identified in glosses.json? What is the relationship with gloss IDs and video/image file names?

**Comment by Woseseltops** [comment]
To do:

Step 1. Packages
* Create a function that turns the Signbank database into JSON, taking only the simple fields.
* Include the references to other tables (languages, keywords, etc) into the JSON.
* Create a function that creates a package, with the json and zipped video and image folders.
* Make the last function accessible from a url.

Step 2. Patches
* Create a function a that makes a copy of a folder, only including files newer than date x.
* Keep a list/database of deleted files and their deletion dates.
* Add an item to this database each time a video or image is deleted.
* Add a field 'last_modification_date' to glosses.
* Update the above field every time something is changed.
* Keep a list/database of deleted glosses and their deletion dates.
* Add an item to this database each time a video or image is deleted.
* Create a function b that returns all glosses with a last_modification_date newer than x.
* Create a function c that returns all glosses/videos/images deleted since date x.
* Create a function that creates a package with the results of functions a, b and c.
* Make the last function accessible from a url.

Alternatively, we could just generate a new package on the server, and compare it with old package that is being referred to in the url argument (should also still be on the server?). This could even be done with the diff Unix tool. Downsides: less control, not sure how this will work with non-text files.

Step 3. Security
* HTTP auth digest?

**Comment by Woseseltops** [comment]
> how are glosses identified in glosses.json

I just discovered dumpdata within Django. I can do this:

`python bin/develop.py dumpdata dictionary.gloss --pks 1,2 --indent 4 > test.json`

and I get this

```
[
{
    "pk": 1, 
    "model": "dictionary.gloss", 
    "fields": {
        "initial_relative_orientation": null, 
        "contType": "0", 
        "phonetVar": "", 
        "iconType": null, 
        "locsecond": null, 
        "wordClass2": null, 
        [...]
        "tokNoGe": null, 
        "namEnt": "2", 
        "blend": null, 
        "StemSN": null, 
        "domhndsh": "3"
    }
},
{
    "pk": 2, 
    "model": "dictionary.gloss", 
    "fields": {
        "initial_relative_orientation": null, 
        "contType": "0", 
        "phonetVar": "", 
        "iconType": null, 
        "locsecond": null, 
        "wordClass2": null, 
         [...]
        "namEnt": "3", 
        "blend": null, 
        "StemSN": null, 
        "domhndsh": "4"
    }
}
]
```

I think we will want to make our own version of dumpdata (this only shows machine values, and no stuff from other tables keywords or translations), but it will be very similar to this.

> What is the relationship with gloss IDs and video/image file names

IDGLOSS-privatekey.extension

**Comment by vanlummelhuizen** [comment]
Some comments on your Steps post:

* Putting videos and images in the package will make it very, very large. Perhaps leave the downloading of the videos and images to ELAN (or any other client for that matter) by just giving a download link? Subsequently, patches also don't necessarily contain videos and images.
* HTTP auth DIGEST is OK with me. Although I don't whether there is a more secure method that is easy to implement. We could investigate in later stage.

**Comment by Woseseltops** [comment]
> Perhaps leave the downloading of the videos and images to ELAN

Indeed a much better idea. Perhaps just a text file with urls then?

> We could investigate in later stage.

:+1:

**Comment by vanlummelhuizen** [comment]
Text files with one url per line sounds like a good idea. Or may be do everything JSON?

**Comment by Woseseltops** [comment]
Created sub-issues #187 #188 #189 as sub issues, so everything is more organized, and @ErwinKomen and me can work in parallel !

**Comment by henrinie** [comment]
I haven't had a deep look into what you are planning so far. This sounds like something we should collaborate on, so I will try to make some quick points.

We might want to agree on the **field names** (if ELAN needs to know what to place where), because you have variable names like *subhndsh* (which apparently means *weak handshape*) and we have that same variable as *weak_handshape*.
Who can understand what subhndsh or domhndsh mean, at least I can't. So our variable names are different and if it matters for ELAN this (feature) would only work with NGT Signbank.
On the other hand we probably don't have all the fields you have and so on.

We have different ways of handling images and videos. I don't know if this would be an issue since we can make our own API according to the guidelines you (or we) decide. Maybe the API should be designed in a way that it is not directly tied to how NGT Signbank (or any other Signbank) is implemented?

The patch functionality:
Is it necessary to always download all the video/image files? Could this be implemented this so that ELAN would download only the files it needs?
For the non-text files we could set *versions*, *id's* or something else that would differentiate them from each others in the json files.
If the cached (ELAN) json would have differences to the latest Signbank json, ELAN would only stream/download the files that it needs **when the user requests those files**. The (ELAN) user would not have to wait before accessing the information he or she needs, and ELAN would only download and cache the files needed, not all of them. If being able to work offline is the priority, then the patching system might be useful, but working offline might lead to mistakes if the user would be working with outdated data. I am not familiar with how ELAN users would use the feature you are planning, so I might be on the totally wrong track.

I don't know too much about different options for authentication, but this question probably needs a lot of thought.

**Comment by vanlummelhuizen** [comment]
@henrinie Some answers to your questions:
@Woseseltops and I agreed upon leaving the downloading of media files to ELAN (or any other client). Signbank only needs to provide a list of files that have been changed (replace most of the time probably) or deleted. 
In ELAN I implemented functions that show sign videos when hovering over an annotation (https://github.com/vanlummelhuizen/ASL-ELAN/issues/8) or when choosing a sign from a CV (https://github.com/vanlummelhuizen/ASL-ELAN/issues/7). Downloading video when needed will take too much time for these functions to work smoothly.

About digest security, as far as I have read about it (which is not a whole lot yet), it is meant to be a bit more secure than sending plain a username and password. To make it a lot more secure, we should use HTTPS instead of HTTP. The next step in security would be quite a big one, so that would be something for later. @Woseseltops, is HTTPS possible for NGT Signbank (preferably enforced)?

**Comment by henrinie** [comment]
@vanlummelhuizen Here are some questions/ideas:

Leaving video downloading to the client is a good decision in my opinion.

**On downloading videos:** How about streaming the videos (and then caching them)? That works pretty smoothly on the Signbank website as the files are only a few seconds long, but of course in ELAN if the response time is not instant, it might make the user experience feel worse.

It might be problematic for some users when the videos start taking tens of gigabytes of space, it might be okay for someones situation but for others it might be impossible. Storage space might be limited especially in shared use PC's around universities and so on. This is a thing to take into account in my opinion, if the user doesn't have cache space available, at least he/she could then stream the videos.

@vanlummelhuizen will the new feature support multiple videos per one gloss? FinSL-Signbank currently supports adding multiple videos for one gloss.

About HTTPS, for this kind of application it is strongly recommended, FinSL-signbank supports HTTPS, I don't see any reason why the NGT-Signbank would not.

**Comment by vanlummelhuizen** [comment]
@henrinie So there should be two options for the ELAN user:

1. Download everything to the user computer for guaranteed fast access and in turn a smooth user experience
2. Stream and cache upto a user defined disk space

We will first implement the first, since that is what @ocrasborn requested. For the second I foresee some difficulties regarding the play back and at the same time caching of videos in ELAN. ELAN uses different media player frameworks on different platforms. The stream from the webservice has to be handled by either those frameworks (don't know if they are all able to) or by ELAN first and redirected to those frameworks while being cached. I will investigate the possibilities.

Downloading multiple videos per gloss is trivial, but we have to think about how these videos would be used in ELAN. I doubt that the user would want to see a handful of videos per gloss if he/she is scrolling through an ECV looking for the gloss he/she is annotating. Therefore, I suggest that there is one main video per gloss, which is displayed in ELAN, and only that one is downloaded and cached. The identification/selection of the main video could be done by ELAN, e.g. by just taking the first in a list, or by the webservice so that it only gives one video url.

**Comment by henrinie** [comment]
@vanlummelhuizen Great points.
The two options sound like a viable solution.

Multiple videos per gloss is something I just wanted to point out, I too think that the user would probably not want to see all of the videos in ELAN.

@Woseseltops @vanlummelhuizen Does a design document for this API/service exist anywhere? I would like to collaborate if possible.

**Comment by Woseseltops** [comment]
Hi @henrinie, sorry for late response!

> This sounds like something we should collaborate on

Ah good to know that this might be useful to you guys too.

> Who can understand what subhndsh or domhndsh mean, at least I can't. 

Yeah these aren't the best names.

> We might want to agree on the field names

Suggestion: maybe I can make it so that all fields for a gloss will be exported (so it's not hardcoded which fields will be exported), and that there is some kind of mapping configuration inside ELAN? So in ELAN you can say use the field named domhndsh for the shape of the dominant hand.

> We have different ways of handling images and videos

Aha, okay! You'll have to change that part of our implementation then.

> Maybe the API should be designed in a way that it is not directly tied to how NGT Signbank (or any other Signbank) is implemented?

I think that design is already pretty much there as a result of this thread. See https://github.com/Signbank/NGT-signbank/issues/187#issuecomment-236115170 and https://github.com/Signbank/NGT-signbank/issues/188#issuecomment-236115444 for the most recent plans, but feel free to suggest changes.

> If being able to work offline is the priority,

It is; the basic assumption for this whole task is that ELAN users have more than enough space to save all of Signbank locally these. In this thread we try to come up with the most efficient way to achieve this. I also like the idea of streaming as a second option though :).

> is HTTPS possible for NGT Signbank (preferably enforced)?

I think we can ask C&CZ to do that for us... I'll ask them right away.

**Comment by henrinie** [comment]
@Woseseltops hi and thanks for your reply!



>     This sounds like something we should collaborate on
> 
> Ah good to know that this might be useful to you guys too.

I am not sure since everyone is having their holidays, but I do think that everyone would like to view Signbank data in ELAN. :smiley: 

>     We might want to agree on the field names
> 
> Suggestion: maybe I can make it so that all fields for a gloss will be exported (so it's not hardcoded which fields will be exported), and that there is some kind of mapping configuration inside ELAN? So in ELAN you can say use the field named domhndsh for the shape of the dominant hand.

On your suggestion: It is a possible way to implement it, but do we want to force the users make settings for themselves? It doesn't sound very user-friendly to me, otherwise it is a good idea.

We could also design the API in a way that we decide what names to use for the variables in the API. Then it would not matter what they are in each version of Signbank (or in any other similar application), we can always add a different (variable) name into the json, according to the specifications of the API of course.
For this and other reasons I suggest that a document of the API specifications is created. Then it is possible for anyone to make an API that ELAN supports.

On the other hand, does ELAN even need to know what fields it is displaying? Do these fields have any relations/significance to anything inside ELAN? If not, then perhaps ELAN could just show all the information it is supplied, making the issue of different variables vague. However maybe there should be a way to indicate in which way to show each exported values in ELAN, as some have multiple values (keywords for example).

> Aha, okay! You'll have to change that part of our implementation then.
> 
>     Maybe the API should be designed in a way that it is not directly tied to how NGT Signbank (or any other Signbank) is implemented?

That is not possible because we just changed it to support multiple videos per one gloss. But it should not be an issue if you can just export the url(s). 



>     Maybe the API should be designed in a way that it is not directly tied to how NGT Signbank (or any other Signbank) is implemented?
> 
> I think that design is already pretty much there as a result of this thread. See #187 (comment) and #188 (comment) for the most recent plans, but feel free to suggest changes.

Could it be possible to change the implementation rules of the API in the second version if it is not possible anymore? It would probably only require minor changes in the exporting (Signbank) side.


> 
>     If being able to work offline is the priority,
> 
> It is; the basic assumption for this whole task is that ELAN users have more than enough space to save all of Signbank locally these. In this thread we try to come up with the most efficient way to achieve this. I also like the idea of streaming as a second option though :).

I understand that it is your requirement. It could be beneficial to make the requirements more general, so that the usage of this feature is not only limited to those using NGT-signbank. I don't know if this could be a problem in our university, but it could be, I have not done any requirements analysis on that part. It definitely could be a problem to other parties that might want to use this feature in the future.

**Comment by Woseseltops** [comment]
Ah, now I understand your viewpoint better. A try at summarizing all ideas:

Approach 1. The gloss fieldnames coming out of all Signbanks are the same and fixed, the info shown in ELAN is fixed.

Approach 2. The gloss fieldnames differ per Signbank, the info shown in ELAN is fixed, the relation is made by a mapping file.

Approach 3. The gloss fieldnames differ per Signbank, the info shown in ELAN is dynamic and depends on what the used version of Signbank provided.

Whatever we choose, we should make sure that:
* The package functionality stays independent of ELAN, so it could be used for other purposes.
* It is easy to change what fields are part of the Signbank output, in case we change our mind.
* ELAN users don't have to do a lot of configuration for it to work.

I believe this can achieved one way or the other with all three approaches, and thus have no clear preference.

Some more responses:

> That is not possible because we just changed it to support multiple videos per one gloss. But it should not be an issue if you can just export the url(s).

No, what I meant is: you can borrow our implementation of the package functionality, but if your videos work differently, you'll have to make some adjustments to our implementation of the package functionality.

> Could it be possible to change the implementation rules of the API in the second version if it is not possible anymore? It would probably only require minor changes in the exporting (Signbank) side.

I'm not fully sure what you mean here, but we're definitely willing to do things different if that makes your life easier.

> It definitely could be a problem to other parties that might want to use this feature in the future.

You are correct, and it's worth discussing, but maybe not in this issue. Let's reserve this issue for talking about packaging Signbank, and talk about other ways to make Signbank-stuff available to ELAN elsewhere.

**Comment by vanlummelhuizen** [comment]
This discussion was not on my radar before, hence the late response.

I can confirm that the current implementation is that of approach 3. Each entry of the search results in the lexicon tab of ELAN can be a tree structure of any kind. ELAN does not provide for the possibility that the user defines which parts of an entry is to be displayed. Therefore the tree structure is defined in Signbank. In Signbank, you can define which gloss fields are to be use by adding them to the list named API_FIELDS in the settings. These fields are complemented by some special ones:

* Translations
* Morphemes
* Parent glosses
* A link back to the entry on the Signbank website.

**Comment by henrinie** [comment]
That is awesome!
So it is possible to show what ever data you want in ELAN, and ELAN doesn't care about the data, it just shows what is provided?

**Comment by vanlummelhuizen** [comment]
> So it is possible to show what ever data you want in ELAN, and ELAN doesn't care about the data, it just shows what is provided?

Yes, with one note: for now it is only text data. But the (tree)structure can be determined in Signbank.

**Comment by ocrasborn** [comment]
@vanlummelhuizen , can this be closed now?

**Comment by vanlummelhuizen** [comment]
Yes.
