### ISSUE TITLE
List view: Add hyperlink on image

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#208]
Add the hyperlink that is now on the glosses also to the image (without any marker like a blue line around the image). So don't remove it on the glosses! (both NGT and ASL)

**Comment by Woseseltops** [comment]
Works now.

**Comment by ocrasborn** [comment]
@Woseseltops , but not for ASL yet, does it? Could you add it there as well?

**Comment by Woseseltops** [comment]
Done, the ASL signbank is up to date again! This took 2 hours or so, because somewhere in the process something went wrong, and I got the error 'unable to access database'. I tried everything to fix it, to the point where I started to panic a bit because I really tried EVERYTHING and it all seemed to be correctly set. In the end it turned out to be that the ASL signbank was pointing to the NGT settings file :( .

**Comment by Woseseltops** [comment]
Can be closed?
