### ISSUE TITLE
Create a Lemma View

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#209]
Multiple Annotation ID Glosses can be grouped under a single lemma by adding a shared Lemma ID Gloss. Currently, nearly all signs have the same value for Annotation ID Gloss and Lemma ID Gloss. We want to start exploiting this Lemma ID Gloss more, and for that we would like to have a separate view similar to the list view, where only Lemma ID Glosses are listed that have more than one Annotation ID Gloss 'under' them. Suggestion:
- Use the same format as the list view, but filter by the presence of multiple Lemma ID Glosses
- Add field Lemma ID Gloss as a first column
- Allow switching to this view by adding a blue button 'Lemma View' on the top left of the list view, left of "Number of matches"
- Allow switching back to list view by a similar button List View on the lemma page

**Comment by susanodd** [comment]
This is kind of related to the discussion in Issue #326. (Import CSV Relation to Other Signs: Which Gloss name should be used? From the above, it would seem that this should not be Lemma ID Gloss since signs can share this.)

**Comment by susanodd** [comment]
@ocrasborn, is the description of the Lemma View given above still as you would like it?

**Comment by ocrasborn** [comment]
I changed one thing (error): the view should filter so that only glosses are shown in cases where one Lemma ID Gloss is shared between two or more Annotation ID Glosses.

**Comment by ocrasborn** [comment]
But, @susanodd : I would much appreciate suggestions for more or better visualisations of this relation. One thing that just crossed my mind: in the detail, list, and variant views, add a symbol next to the Annotation ID Gloss that highlights _that_ there is another Annotation ID Gloss that is linked to the same lemma (with hyperlinks to jump to them). Perhaps just a mini icon with a tooltip popping up with the other glosses?
But please add better ideas!

**Comment by susanodd** [comment]
@ocrasborn, question: Do you want a Lemma Detail View? (With limited information.)
I ask because in the List View, there are hyperlinks to the various fields for each Gloss.
So there is a link on fields annotation_idgloss and annotation_idgloss_en and idgloss.
That last one is the Lemma. But currently, this is just a link to the (same) gloss.
I'm looking at the results of searching on 'aaien'. It looks like the various NAAIEN-A, NAAIEN-B, NAAIEN-C might belong to the same Lemma Group NAAIEN (which doesn't exist).
(See screen shots below.)

**Comment by susanodd** [comment]
![gloss-list-view-search-aaien](https://user-images.githubusercontent.com/24272544/31998939-d6ecc272-b991-11e7-9a66-5adee76971b0.png)
![lemma-view-search-aaien](https://user-images.githubusercontent.com/24272544/31998947-db238466-b991-11e7-8162-7fe063db967c.png)

**Comment by susanodd** [comment]
I'm still working on it, so this is a working version. There is a Django feature that allows for grouping of the objects. But then, the (Lemma) object groups don't have the (right) links.
For example, the two signs in Lemma Group AAIEN actually are linked to different (Lemma Group) Glosses. (Because there is no Lemma Group object.) (The Lemma Group AAIEN is actually not linked to anything.)
Maybe you can say how you would expect the above to work?
According to the description of this issue, I ought to hide those rows where there is only one Gloss in a Lemma Group. On my local copy, I want to make a new Lemma Group NAAIEN so that I can have more data to experiment with. Then I realised there aren't actually any Lemma objects.

**Comment by susanodd** [comment]
I made a (local) Lemma NAAIEN to show more grouping. I removed the hyperlinks for Lemmas from the Gloss List View.
![lemma-view-search-aaien-lemma-naaien](https://user-images.githubusercontent.com/24272544/32003364-13522da8-b99f-11e7-95b5-8f8e316c4f85.png)

**Comment by susanodd** [comment]
Okay, now only Lemma Groups with more than one Gloss are displayed in the Lemma View.
I made it so that sorting (the default sorting is on Lemma ID gloss) sorts next on Annotation ID Gloss: Dutch. (So that the Lemma Groups are still sorted.) There are no sorting buttons for the Lemma View. (On my local database, I added more glosses to Lemma Group OPEN for the example.)

![lemma-groups-search-open](https://user-images.githubusercontent.com/24272544/32053643-3a10e35e-ba5c-11e7-90d7-c18d6936ddc1.png)

**Comment by susanodd** [comment]
Okay, this has been pushed to github.
Things to notice: the Sorting up and down arrows that appear in the Gloss List (below the column headers) are not present in the Lemma View. (The Lemma's are sorted based on the Lemma Group.)
The pagination is still part of the Lemma View, but if you set the number of things per page really low, then some pages at the end can be empty, depending on how many Lemma Groups are singletons (and ignored in the display).

**Comment by vanlummelhuizen** [comment]
This is live.

**Comment by ocrasborn** [comment]
:-)
