### ISSUE TITLE
Allow selection of dataset(s)

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#230]
* Being the dataset(s) to which searches apply
* Could be one or more --> list of dataset with checkboxes?
* Make this a separate page where the user goes via a menu item Datasets > Select dataset. See #229 
* If user has access to only one dataset, perhaps the menu item should be hidden altogether?

**Comment by vanlummelhuizen** [comment]
@ocrasborn Done and live. Also made the menu items (#229).

**Comment by henrinie** [comment]
I am not sure if this is the same thing, but I will explain how we have implemented this.
On the search page there is a box that lists all the datasets the user has access to. From that list the user can select none (meaning all are selected), one or many.

There really is no need for a page, unless you want to save your selection. Users will most likely have access to one dataset, so they don't need to select anything.

**Comment by henrinie** [comment]
![signbank-dataset-search](https://user-images.githubusercontent.com/14230626/30421402-555b97cc-9945-11e7-8a76-f0fd96c489d9.png)

**Comment by susanodd** [comment]
I just added the facility to assign the Dataset field in the Gloss Detail View.
It is checked if the selected Dataset is public or if the user has permission for this Dataset.

**Comment by henrinie** [comment]
@susanodd This could be easily done in the django-admin. In my opinion having such choice on the gloss page is not very useful, as the value should never be changed.

**Comment by susanodd** [comment]
Hmmmm. @vanlummelhuizen will have to answer that, he was the one who said to add the functionality.

**Comment by vanlummelhuizen** [comment]
@susanodd @henrinie I believe in NGT-signbank datasets will be used to make glosses available/editable to certain users/user groups. I can imagine there might be glosses that need to change dataset at some point (without necessarily changing sign language). @ocrasborn will know for sure.

**Comment by ocrasborn** [comment]
I can't think of a use case right now, but yes, if they stay within a language that's a possibility we might one day want to explore.

**Comment by henrinie** [comment]
> I can imagine there might be glosses that need to change dataset at some point (without necessarily changing sign language).

This is an interesting idea I have never thought of before. I can't think of a situation in which a gloss would change dataset, could your provide some example so that I could understand this use case better?

**Comment by ocrasborn** [comment]
If you have different data sets for the same language, it could simply be that you mis-place a new sign. But also from a more linguistic point of view, if you create subsets for a particular study, you might want to move new items your created for the smaller study to the more generic dataset for that language.

**Comment by henrinie** [comment]
If you misplace a new gloss, you can easily change its dataset via django-admin (so no need to implement any features for this in my opinion).

If you want to use the same gloss in multiple datasets (like creating subset of glosses in one dataset), perhaps the key (ForeignKey) that links a Gloss to a Dataset should be changed to a ManyToManyField, so that one Gloss can have/be part of multiple Datasets?

**Comment by ocrasborn** [comment]
@vanlummelhuizen : un-selecting NGT in the Dataset menu does not yet filter out NGT results in the search (or Show all signs from the Signs menu).

**Comment by susanodd** [comment]
@ocrasborn, I've been working on this. Below please find some example screenshots.
![dataset-selection-ngt](https://user-images.githubusercontent.com/24272544/33371679-d023bc86-d4fb-11e7-972d-1d32df80abaa.png)
![datasets-ngt-selected](https://user-images.githubusercontent.com/24272544/33371689-d9c3d848-d4fb-11e7-8e5f-cb428d43e713.png)
Above, the Dataset NGT has been selected.
Below are the two queries, one for Glosses, the other for Glosses and Morphemes. (The query itself is a show all.) There are two screenshots so you can see that the Total of the Dataset page includes both glosses and morphemes.
![gloss-list-selected-ngt](https://user-images.githubusercontent.com/24272544/33371755-0bd54042-d4fc-11e7-8faf-832e27049980.png)
![gloss-list-gloss-or-morpheme-ngt](https://user-images.githubusercontent.com/24272544/33371758-0f8079d2-d4fc-11e7-9151-4d5a279fa411.png)

**Comment by susanodd** [comment]
Now here's the second example, now no datasets have been selected.
![datasets-nothing-selected](https://user-images.githubusercontent.com/24272544/33371835-4b50e9e2-d4fc-11e7-9649-5f2d5a90edf8.png)
Below is the result of the query for Glosses (show all, for all datasets one is allowed to view.)
![gloss-list-all-datasets](https://user-images.githubusercontent.com/24272544/33371893-72d9b3cc-d4fc-11e7-8d68-e0b79840002a.png)
In this results screenshot, the text "Selected datasets:" (not yet in trans) probably ought to be something else, since nothing was actually selected. Maybe just "Datasets:".

Does the above dataset selection for the Gloss List View work the way you would like it to work?

**Comment by susanodd** [comment]
Oh, a comment, it would seem the Django "guardian" is not working properly. I only have Access to View two datasets, but the (same code) seems to give different results in the Gloss List query since also the TestDatasetMicha, Norwegian Sign Language, and Shanghainese are also shown. We noticed this problem before, but it seems not to be working.

**Comment by susanodd** [comment]
Okay, I fixed the bug about the guardian.
Here are the screenshots for the case when no datasets are selected. The Gloss List View (with show all glosses and morphemes) shows the datasets that the user has Access to.
The Select Dataset feature narrows the query list results to the Selected Datasets, otherwise it's all the Datasets the user can view.

![datasets-available-access-but-not-selected](https://user-images.githubusercontent.com/24272544/33375935-fd0f2a2c-d50b-11e7-958d-cdc3c9ba021b.png)
![gloss-list-datasets-with-access](https://user-images.githubusercontent.com/24272544/33375962-1947463e-d50c-11e7-84aa-7a70467652da.png)

**Comment by susanodd** [comment]
This has been pushed to github, master branch.

**Comment by Woseseltops** [comment]
@vanlummelhuizen and @susanodd , you seem to be working on this, so I'll assign the issue to you guys. In case it's already fully working, reassign to Onno so he can verify and close.

**Comment by ocrasborn** [comment]
I'm happy; shall we close this, @vanlummelhuizen ?

**Comment by vanlummelhuizen** [comment]
If you are happy, I am happy @ocrasborn !
