### ISSUE TITLE
Show list of datasets the user has access to

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#231]
* See #223 
* On a new page under menu item Datasets > Available datasets; see #229 
* List all datasets in the database (first column), with in the second column Access: yes/no ("Access" being the column header), and in the third column the present number of signs in the dataset

**Comment by vanlummelhuizen** [comment]
@ocrasborn First version is now live: /datasets/available/
Datasets can be added via de Django admin. When editing a (new) dataset, user permissions per dataset object can be edited by clicking 'Object permissions' in the top right corner.

**Comment by ocrasborn** [comment]
Nice!
* Not sure how group and user permissions interact here (and I cannot set group permissions without also listing a user, is that a bug?): do dataset user permissions now take precedence over (overall?) group permissions?
* After saving 'Object permissions', I see only question marks for missing images; should be green checkmarks and red crosses?

**Comment by vanlummelhuizen** [comment]
@ocrasborn 

> Not sure how group and user permissions interact here (and I cannot set group permissions without also listing a user, is that a bug?): do dataset user permissions now take precedence over (overall?) group permissions?

Group and user permissions interact as follows (as far as I can see after some testing): if either one has a permission set, the user has the permission. There is no explicit 'no permission', just 'permission' or blank, which is interpreted as 'no permissions'. Another way to look at it: if a user has a permission set in either the user-permissions or group-permissions, the user is allowed to do the action. Otherwise, the action is blocked.

> After saving 'Object permissions', I see only question marks for missing images; should be green checkmarks and red crosses?

This is solved now. (@Woseseltops, it was necessary to copy the img directory of the Guardian package. Same as the admin-img directory. Symbolic link didn't work. Any thoughts?)

**Comment by henrinie** [comment]
The file issue should be solvable with the collectstatic command, whicj
should copy all the static files from apps (including admin) into the
folder specified in settings.

13.9.2017 12.30 "Micha Hulsbosch" <notifications@github.com> kirjoitti:

@ocrasborn <https://github.com/ocrasborn>

Not sure how group and user permissions interact here (and I cannot set
group permissions without also listing a user, is that a bug?): do dataset
user permissions now take precedence over (overall?) group permissions?

Group and user permissions interact as follows (as far as I can see after
some testing): if either one has a permission set, the user has the
permission. There is no explicit 'no permission', just 'permission' or
blank, which is interpreted as 'no permissions'. Another way to look at it:
if a user has a permission set in either the user-permissions or
group-permissions, the user is allowed to do the action. Otherwise, the
action is blocked.

After saving 'Object permissions', I see only question marks for missing
images; should be green checkmarks and red crosses?

This is solved now. (@Woseseltops <https://github.com/woseseltops>, it was
necessary to copy the img directory of the Guardian package. Same as the
admin-img directory. Symbolic link didn't work. Any thoughts?)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Signbank/NGT-signbank/issues/231#issuecomment-329112475>,
or mute the thread

**Comment by vanlummelhuizen** [comment]
Forgot to mention, I get an exception when doing collectstatic (at least on my local instance):
```
django.core.exceptions.ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.
```
Hence the copying by hand.

**Comment by henrinie** [comment]
@vanlummelhuizen That directory needs to be specified in the settings. It is the directory where the (static) files will be copied to, so that they can be served by the web server.
Hope this helps

**Comment by ocrasborn** [comment]
Done, @vanlummelhuizen ?

**Comment by vanlummelhuizen** [comment]
I believe so. I will close it now.
