### ISSUE TITLE
URGENT: ASL Signbank templates use wrong gloss field

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#239]
This is not so much a bug in the software as an NGT>ASL migration issue. We discovered by accident that the ECV export for ASL uses the correct gloss field (Annotation ID Gloss: English), but that the templates appear to (incorrectly) use the Annotation ID Gloss: Dutch. When entering a gloss, the value for Annotation ID Gloss appears to be used to automatically fill both fields. But when a change in the gloss is later made, discrepancies between the two can occur, it seems. We found 'yes' in the ECV, but see YES in the Signbank interface. In Admin/Glosses, the upper and lower case versions were in the two different Annotation ID Gloss fields. I already changed 'yes' to YES, but replicated it with onnotest2.
I know we discussed the choice of field for ASL before, not sure what we thought was best. Important now is that it is consistent. Given that the ASL users have been making changes in the interface, perhaps it would be best to set the gloss field in the ECV to match that of the interface (thus: Annotation ID Gloss: Dutch). But then: this is counterintuitive in the admin interface: Dutch should play no role in ASL Signbank. (Looking ahead at the 'dataset' functionality: this is related to the revised use of language suggested by @henrinie , which I like. See discussion under #224 )
@Woseseltops , could you look into this?

**Comment by Woseseltops** [comment]
I understand your confusion, sorry @ocrasborn . The system I had in mind works different from what you seem to expect. I envisioned two 'id gloss' fields:
1. The main one, which uses the spoken language of the area it is used in. For NGT, this is Dutch, for ASL this is American English.
2. An extra one in English so that the international research community can follow along. If the main one already was in English, this extra field can be disabled with the setting SEPARATE_ENGLISH_IDGLOSS_FIELD 

What makes this confusing is that these fields have different labels in various places: 


NGT Signbank

|         | Site           | ECV  | Admin |
| --- | ---| ----- | -----  |
| Main annotation ID gloss field | Annotation ID gloss: Dutch | nld | Annotation ID gloss: Dutch |
| Alternative annotation ID gloss field | Annotation ID gloss: English | eng | Annotation ID gloss: English |


ASL Signbank

|         | Site           | ECV  | Admin |
| --- | ---| ----- | -----  |
| Main annotation ID gloss field | Annotation ID Gloss | - | Annotation ID gloss: Dutch |
| Alternative annotation ID gloss field | - | eng | Annotation ID gloss: English |


Knowing this, do you agree that these things should be changed:
* In the admin, the label for the main field should be changed, and the whole field for the alternative field should not be visible.
* In the ECV, the main field should be used instead of the alternative one.

**Comment by ocrasborn** [comment]
I agree, @Woseseltops . Thanks for the clear overview.

**Comment by Woseseltops** [comment]
I think it's working now!

**Comment by Woseseltops** [comment]
For clarity the current situation for the ASL Signbank is (if I made no mistakes):

|         | Site           | ECV  | Admin |
| --- | ---| ----- | -----  |
| Main annotation ID gloss field | Annotation ID Gloss | eng | Annotation ID gloss |
| Alternative annotation ID gloss field | - | - | - |

**Comment by ocrasborn** [comment]
Thanks @Woseseltops !
