### ISSUE TITLE
Using return to start a query initiates a CSV download

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#250]
If I type something in the gloss/transl. eq. search fields in the search form (not in the menu bar), and confirm the query by hitting enter, a CSV download starts. I can't imagine this was intended as a function, but either way, please change it to executing the query. (Problem in Safari/Firefox on Mac, Chrome on Windows)

**Comment by Woseseltops** [comment]
I think I fixed it. The problem was that with the dropdown menu @ErwinKomen added (which I think by the way is a very elegant solution UI wise), the first button was no longer recognized as a true 'submit button'. The first submit button was the second button, which was the CSV download. I fixed it by added a hidden submit button before it that does the search, which works on Chrome and Firefox on Ubuntu. Could you check on a few browsers on the Mac, @ocrasborn ?

**Comment by ocrasborn** [comment]
Works on Safari, Firefox, Chrome, thanks.
