### ISSUE TITLE
Pictures disappear when changing glosses

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#276]
The ASL team noticed a bug we hadn't come across yet, but it appears to work the same for NGT: the reference to images (the image file name?) is not correctly updated when changing a gloss. For videos, no problem, but pictures get lost in this way.

**Comment by henrinie** [comment]
Do you mean when changing the idgloss field?
This might be due to the videofile changing its name/folder, but the image not.

**Comment by Woseseltops** [comment]
Done. Weird, this code for images was simply not there, it never occurred to me. Extra complicating factor is that the code looks at files existing on disk for the file extension, but this of course cannot be done if it wants to know the appropriate future location so it can move the file. Works now, though.

**Comment by Woseseltops** [comment]
Note: commited, but not pushed yet (or pulled at the Dutch SB), because I have to review Susans code first before merging it.

**Comment by ocrasborn** [comment]
We can't replicate it anymore. I'll keep the issue open, and as soon as it re-appears, I'll add the priority label again.

**Comment by Woseseltops** [comment]
@ocrasborn , what does the 'top priority' label mean in this issue? Because I think we're still waiting until someone discovers how to reproduce this again. I'm asking because 'top priority + assigned to me' means that it will be on top of my list of things to do, and I'm trying to keep to keep that list clean. How about a 'cannot reproduce' tag?

**Comment by ocrasborn** [comment]
Not sure why I re-added the label. No recent complaints anymore, I'll just close the issue altogether.
