### ISSUE TITLE
Remove Dutch gloss fields in two places for ASL

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#296]
The Annotation ID Gloss (Dutch) field still appears in two places, please hide:
* In the CSV export
* When clicking 'Add new sign' below the search form
Instead of this field, please add the field Translation Equivalents (keywords) at the right

**Comment by vanlummelhuizen** [comment]
OK, I am a bit confused. Annotation ID Gloss (Dutch) is called annotation_idgloss in the database and may not be empty. Should I make it so that is may be empty, so that it may be hidden on the 'Add new sign' form? Or do you want annotation_idgloss to be the main Annotation ID-gloss and just hide the '(Dutch)' part in the user interface (and hide the Annotation ID Gloss (English) altogether)?

**Comment by henrinie** [comment]
I'd be careful when touching the idgloss field. I would assume it to be the main field for idgloss. If the ASL users are using some other field, some problems might arise.

I would assume that Onno wants to hide the English field, and remove the "Dutch" part.

**Comment by ocrasborn** [comment]
Better discuss this with @Woseseltops next week, as maybe this is a good time to rethink how we've done this given that for the upcoming 'multilingualisation' we will be adding glosses in further foreign languages. (See Milestone https://github.com/Signbank/NGT-signbank/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Multiple+Languages+%2F+Datasets%22)

**Comment by vanlummelhuizen** [comment]
Couldn't agree more.

**Comment by Woseseltops** [comment]
Fixed this for now with the setting SEPARATE_ENGLISH_IDGLOSS (which is false for ASL, because the main idgloss IS the English field, so no second separate one is needed). 

However, I expect this approach will soon be deprecated. @vanlummelhuizen is working on a system where the translation language can be dynamic based on the translation languages available for a dataset. Still, I think my quick fix was useful because now he has an easy keyword to search for and get all places in the code that need updating in one go B) .

Happy, @ocrasborn  ?

**Comment by ocrasborn** [comment]
yes :-)
