### ISSUE TITLE
Create help pop-ups

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#301]
In several places in the interface, it would be good to have contextual help pop-ups like you see in some websites: a subtle small yellow circle with a question mark (or something like that) that you can hover over, so that a little pop-up window appears with explanations. We'd like to have that too, starting with some quick hints on regular expressions for all text search boxes:
^A, starts with A
$A, ends with A
A|B, A or B
.*, find all strings in this field
\(, use backslash to find special characters in field

**Comment by henrinie** [comment]
Bootstrap3 has a component for this: http://getbootstrap.com/javascript/#tooltips

**Comment by vanlummelhuizen** [comment]
Something like this:
![signbank_tooltip](https://cloud.githubusercontent.com/assets/16682631/24506362/83ab5d90-155d-11e7-8210-9ef88e43db60.png)

**Comment by ocrasborn** [comment]
Exactly! Maybe left-aligned with a bit of a space instead of the comma as a separator would look nicer. And please add "A, contains A" at the top

**Comment by ocrasborn** [comment]
We can see it now, it looks good @vanlummelhuizen! One small text error to be repaired: the text after .* is not correct, should be as in the screen shot above.

**Comment by ocrasborn** [comment]
Oh, and I don't see it appear on the ASL Signbank yet, right?

**Comment by vanlummelhuizen** [comment]
@ocrasborn I corrected the error and made the labels translatable in one go. 

I invented "confirm solution" so that you know a solution is made, but it needs to be put online and then checked. It also helps me to filter out things I have finished (for now). Perhaps a "to be put online" label should precede the "confirm solution" label. Or perhaps another procedure is better. Any ideas? @Woseseltops ?

**Comment by ocrasborn** [comment]
Thanks @vanlummelhuizen !
Let's not create too much administration. How about changing the 'confirm solution' to simply 'ready'? I'll then close the issue after Wessel has put it online and found that it works like we expected.

**Comment by Woseseltops** [comment]
> Or perhaps another procedure is better. Any ideas? @Woseseltops ?

A system I was already using with Onno is the assignee system: when I expect Onno to look at something, confirm something, test something, I simply make @ocrasborn the assignee. Maybe @vanlummelhuizen can make me assignee if something needs to be put online? Because then it simply turns up in the list of things I am or should be working on.

**Comment by vanlummelhuizen** [comment]
Alright, let's do that. I did it with #283 already. Remove label 'ready' again?

**Comment by ocrasborn** [comment]
I did. :-)
