### ISSUE TITLE
Some problems creating new signs

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#309]
"Als ik een glosvoorstel wil doen in Signbank kan ik geen ja aanklikken bij hokje of dit een glosvoorstel is en komt er een error als ik een filmpje probeer te uploaden...." (Fri 21 Apr, 10:10)

**Comment by Woseseltops** [comment]
The problem with the 'is new sign' checkbox was something sloppy that was now being revealed by the moved by Python3; I've fixed it in 11c71d43bea91666dcc0ece6ec6d7e014cde6e81 . 

The uploading problem is because I've not yet installed the external stuff by @vanlummelhuizen , which does things (I think) like video resizing, extracting the poster image, and automatically updating counts; this problem was also mentioned by you in #308

**Comment by Woseseltops** [comment]
Uploading videos works again, I think!

**Comment by ocrasborn** [comment]
Yes, it is for our regular signbank clips, it seems, and extracting a poster image works too. But for another type of movie I get an error message of a type that I wouldn't expect, see screenshot.
![screenshot 2017-05-03 13 03 24](https://cloud.githubusercontent.com/assets/10242207/25658071/4222c480-3001-11e7-8c06-8c98183fc564.png)

**Comment by Woseseltops** [comment]
Weird, this was a completely different problem: the file was succesfully uploaded, but uwsgi (=connection between python and apache) didn't want to display it. I can reproduce the problem by downloading the file from Applejack and uploading it again in the SB interface.

The reason seems to be that the file has no 'group' read and write rights (which are needed to serve the file), and apparently these rights remain as they are when the file is uploaded. That is, apparently, if you restrict the permissions for a particular file on your local machine, and then upload it, it won't be displayed because of these restricted permissions. 

I have (1) fixed the permissions of this particular file and (2) created #316. Up to you, @ocrasborn, to prioritize #316 and close this issue if you're satisfied :).

**Comment by ocrasborn** [comment]
:-)
