### ISSUE TITLE
ECV not accessible?

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#311]
ELAN files started complaining that the ECV is no longer accessible at http://signbank.science.ru.nl/static/ecv/ngt.ecv; if I open the url in a browser, it doesn't have the file.

**Comment by Woseseltops** [comment]
Ha, I finally figured this out. With the move from Python 2 to Python 3, we were also forced to change from mod_wsgi to uwsgi (= the module that makes the connection between web server Apache and Django/Python). Unlike mod_wsgi, uwsgi didn't like it that it had to look for the ecv file in the writable folder outside the repository. After trying various things, I've settled on changed the Apache config so the path /static/ecv is served by Apache itself, instead of going through mod_wsgi like the rest of the application.

**Comment by ocrasborn** [comment]
I can see the xml in the browser again now, but ELAN still complains it can't find it and therefore uses the cached version. Not sure why; we'll wait for @vanlummelhuizen to get back from holiday to look at this.

**Comment by henrinie** [comment]
@ocrasborn your url doesn't seem to start with **https://**, could that be the problem?

**Comment by Woseseltops** [comment]
Aah of course thanks @henrinie . At Spitfire, we had it set up like all http urls would redirect to the https version... except the ecv one, because Elan does not support https. This exception was not set up at Applejack, but now it is! :)

Does it work @ocrasborn ?

**Comment by ocrasborn** [comment]
Yes it does, @Woseseltops !
