### ISSUE TITLE
Include morphemes in CSV export

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#315]
I'm not sure we did this on purpose, but even if they are in the search result, morphemes don't export to the CSV. Please make sure they do, so that the user can control what will be in the export by searching over either signs or morphemes or both.

**Comment by vanlummelhuizen** [comment]
Part of the problem lies in the fact that when searching for signs and morphemes the search_type is set to 'signs' when clicking the CSV button.

When searching for morphemes only, the CSV button does not work at all.

**Comment by vanlummelhuizen** [comment]
The first part of my previous comment is solved.

**Comment by vanlummelhuizen** [comment]
This second part took me a while. Clicking the CSV button did not result in a request being send to the server because some fields were required. This was not immediately clear because in Gloss search it worked, the search button did not suffer from this problem and the red outline of the required fields were not visible when all panels are collapsed.

Perhaps an indication that the form is not completely correct should also appear when all panels are collapsed? Although I am not sure that the form could be incorrect now that the 'required' constraint is overstepped (also done in the Gloss search).

**Comment by Woseseltops** [comment]
Just checked this, works.
