### ISSUE TITLE
Enable internationalisation/localisation

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#32]
of interface + field names + field values
--> https://docs.djangoproject.com/en/1.7/topics/i18n/translation/#

**Comment by ocrasborn** [comment]
Wessel, will you split this up in sub-issues if needed?

**Comment by Woseseltops** [comment]
The first things are working. I've added two flags to the interface that change the language used (at the time of writing only visible in the gloss detail view), and wrote a wiki page that tells translators where to find all stuff: 

https://github.com/Woseseltops/signbank/wiki/How-to-translate-texts-for-Signbank

To do:
* Make the non-selected flag go gray/white.
* Intergrate Henri's work with the templates.

**Comment by Woseseltops** [comment]
By the way, the language chosen is forgotten after the browser is closed. Do we want to save language preferences per user in a database somewhere? Definitely possible, but I expect it to take 4 hours or more.

**Comment by ocrasborn** [comment]
Yes, please do store the language setting per user. Perhaps related to #72? We probably want to work towards storing more settings and user actions.

**Comment by Woseseltops** [comment]
@richardbank @ocrasborn I noticed Richard had already zealously translated everything there was to translate; I compiled his work, so it's now visible in Signbank. I have to admit that these phrases were extracted automatically, so I have no idea where on the website his work will be visible (but I expect somewhere in the Django admin).

Anyway, I'm now adding translation tags everywhere on the site, so the list will grow. If you feel like translating, just check the .po file again, and there will probably be something new (if I've worked on this issue).

Finally, I want to share some enthousiasm about Django, because the whole internationalization functionality turned out to be much smarter than I expected. I already told you that the message file (the file you edit) is generated automatically by scanning the whole project, but it turns out that it also makes sure that it does not throw away or overwrite any exisiting translations if I generate the file again... and if it finds something new to add to the list, it even looks for similar existing translations. Wow!

**Comment by Woseseltops** [comment]
Done:
* Extra info (settings, preference, user stats) can now be saved for each user, and are visible in the Django admin where you'd expect them
* When you change language, this is saved in your profile.

To do:
* When you log in, the language should change to what was saved

**Comment by Woseseltops** [comment]
Note: I'm working locally today because of the Ponyland upgrade, and I lost quit a lot of time to the 'save language to the user profile' feature not working. The solution turned out to be to edit the field in the Django admin at least once. This might be a problem for the online version for other users as well.

**Comment by ocrasborn** [comment]
[Hi Wessel! I'm starting to get back to work as you see.] Perhaps it's a good idea to start compiling (rephrased) comments like these on a special wiki page for developers, as the start of a developer manual. Could you do this, and add some other difficult issues that you spent a lot of time on to solve?

**Comment by Woseseltops** [comment]
See #78 :)

**Comment by Woseseltops** [comment]
I've added a 'Dutch content' field to the pages, so there are two text fields to edit now in the Django admin for pages. The currently selected language determines which field is used. 

I originally wanted to add content like this to the .po file, so you had all translations in one place, but didn't do so because:
* Some content has layout, which would be harder to get right in a flat text file.
* The Django language system is more automated than I thought; I don't want to fiddle with existing Django tools.

For completeness, I should add that I found a few Django extensions that claim they let you translate database values in some way, but I cannot get a good idea of their quality. Also, I would guess that the trouble of installing them isn't worth the functionality that they add. But it's good to keep in mind they exist.

**Comment by Woseseltops** [comment]
( now also visible on signbank.science.ru.nl )

**Comment by Woseseltops** [comment]
I just spent 1.5 hour to display Dutch page titles, but with no luck. I must be overlooking something stupid. Changes here: a3512dc

**Comment by Woseseltops** [comment]
I look at it again, and it's fixed in 15 minutes. Turns out, the menu wasn't displayed using page objects, but special made dictionaries. These dictionaries of course didn't contain my new field title_dutch. Again forgot to mention issue in the commit : https://github.com/Woseseltops/signbank/commit/6659cda7c42ed12b49de029bb83811976f3b0d26

**Comment by ocrasborn** [comment]
To do, as far as I can see:
- Field names for all fields that are hidden in the panels Phonology, Morphology, Semantics in the detail view
- Field values for those flelds of all Django-lists
Or is there something more that I overlooked?

**Comment by Woseseltops** [comment]
The field labels (first bullet) can now be translated. Turned out to easier than I thought because this functionality is built in to Django.

**Comment by ocrasborn** [comment]
eh... but I don't see anything in the .po that refers to the field names. Am I missing something?

**Comment by Woseseltops** [comment]
Haha, I regenerated the po file after I only added handiness, so that's there: https://github.com/Woseseltops/signbank/commit/ef57466289b561175a3754a08c78e22e0dc77ca0#diff-406e8b46071db4d26d72e274ff935ee9R1931 .

I've now added all other fieldnames and regenerated the po.

**Comment by Woseseltops** [comment]
I've added a Dutch_name field to the field choices in the admin, and the result of it is already visible in the detail view. This was quite a lot harder than I expected, as the dynamic field choices we're using is not something that's supported out of the box; I added it to Django myself. To make the translations work, I had to rewire a whole part of the code.

Btw, when you edit something it still does show the English names; I already have an idea how to do that, but that won't fit into today :).

**Comment by Woseseltops** [comment]
The choice lists while editing are now also taken from the english_name or dutch_name properties. This again required changing a lot of complicated code and a lot of corner case fixing afterwards. My head still hurts :)

**Comment by Woseseltops** [comment]
A corner case I missed: directly after you edit, it still showed English until you refreshed. Works now!

PS
Thanks! My head feels better now, and I won't get scurvy either :).

**Comment by Woseseltops** [comment]
I've discovered another small thing to do: some text is added by Javascript, most notably the 'Edit' button which is changed into 'Turn off edit mode' . I plan to fix this by injecting some Javascript into the template, or this way: https://docs.djangoproject.com/en/1.8/topics/i18n/translation/

**Comment by Woseseltops** [comment]
Done; I moved the things to translate from the Javascript into the template. I think this is also more elegant, so we're not mixing UI with inner workings.

**Comment by ocrasborn** [comment]
Found one more thing: the button "Edit Page" that appears on pages that are filled in the Django admin Pages section (what is the elegant way of saying this?) needs translation; also needs to be moved from javascript to the template?

**Comment by ocrasborn** [comment]
And one last thing in the .po file that you'll need to look at Wessel: line 2473ff gives an error when compiling to .mo if I remove the fuzzy marker, apparently because the variables are on different lines in the English and in the Dutch versions.
(Note that the python-format marker on the same line should stay there).

**Comment by Woseseltops** [comment]
> the button "Edit Page"

Done. Simply was in a template I didn't check for translations.

> pages that are filled in the Django admin Pages section (what is the elegant way of saying this?)

"Django pages editable in the admin"?

> line 2473ff gives an error when compiling to .mo if I remove the fuzzy marker, apparently because the variables are on different lines in the English and in the Dutch versions.

Not fully sure, but I think I fixed it in https://github.com/Woseseltops/signbank/commit/7139f8aa4d3ce9cd2465e512ac6f5c8bb852ab2f ... soource should have been source.

**Comment by ocrasborn** [comment]
Overlooked something prominent: All field names in the search form are still to be translated.

**Comment by ocrasborn** [comment]
* Done some of them in dictionary/forms.py. 1820badf402920a035323a1bca7afd791efa6b06
* Can't work out why most of the search field labels are not included in the .po file.
* There's a few field choice lists that are still in models.py that had better be moved to the Django admin field choices: RELATION_ROLE_CHOICES, DEFN_ROLE_CHOICES. (Found them in a search for some untranslated items, and noted that all the old choice lists are still embedded in models.py; better clean up now that they have been moved to the Django admin?
* Generating the po file leads to some errors, could you check those out @Woseseltops ? (Possibly related to the distinction between _(u 'value') and _("value")? Simply tried to copy what I saw elsewhere, and understand the u is for unicode, but I don't quite understand what I was doing :-).)

**Comment by ocrasborn** [comment]
Also to do, on search page:
* 'Search' button
* 'Add new sign' button
* String 'Results per page'

**Comment by ocrasborn** [comment]
Problem in translating field values: I cannot translate 'Metalinguistic' to 'Metalinguïstisch' (SemField no. 26), signbank crashes on the umlaut. Come on! Grow up Django! @Woseseltops ?

**Comment by Woseseltops** [comment]
I found something else: when adding a new row to something in the detail view, like a new other video or morphology definition, the field choices are always in English. I can of course fix this, but I should add that this would take a lot of time (>1h) compared to how small this feature is.

**Comment by ocrasborn** [comment]
OK, let's put that aside for the moment, then; can you put it in a separate issue so that we don't forget to address it later, but can close the present issue shortly?

**Comment by Woseseltops** [comment]
> Also to do, on search page:
> 'Search' button
> 'Add new sign' button
> String 'Results per page'

All added to the .po now

> In models.py under class 'Meta' there's a list of permissions with strings that need translation tags

Are you sure? Because the end user will never see them, you only see them in the admin.

> Generating the po file leads to some errors, could you check those out

Do you mean (1) warnings in generating the po or (2) errors in generating the mo? Assuming the first, you must be talking about:

   warning: internationalized messages should not contain the '\r' escape sequence

This is something included in some automated test files, and has nothing to do with Signbank. I think it verifies what the Django internationalization module does with that \r . In any case, nothing to worry about.

> Can't work out why most of the search field labels are not included in the .po file.

As far as I can see, they are, translated and everything. They just don't show up on the website; working on that.

> Problem in translating field values: I cannot translate 'Metalinguistic' to 'Metalinguïstisch' (SemField no. 26), signbank crashes on the umlaut

Working on it.

**Comment by Woseseltops** [comment]
Fixed both things:
* You can now see all translated labels (was just a matter of Django grabbing the translations to early, set it to 'lazy').
* The FieldChoice problem was related to the fact that I set Fieldchoices to display in the format topic: english_name, dutch_name (machine_value). When one of these fields contained a weird char, the admin crashed. I fixed this by automatically replacing weird chars.
