### ISSUE TITLE
Tags don't appear in the list view anymore

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#323]
related to implementation of #317 ? Can't imagine why it would be, but it seems to have happened in the last one or two weeks

**Comment by Woseseltops** [comment]
Really unsure what happened there; the functionality gloss.tags stopped working all of sudden. Anyway, when investigating this I discovered that the 'requesting tags' in the detail view works completely different. When I use this approach in the list view, it works again; weird.

Note to self: not pushed to github yet, because @vanlummelhuizen has some stuff pushed that I cannot pull yet.

**Comment by Woseseltops** [comment]
@ocrasborn once you're happy we can close this, push will come later

**Comment by ocrasborn** [comment]
Happy.
