### ISSUE TITLE
Changing the interface language appears to be broken

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#330]
Can't change on Safari; page keeps reloading
Update: and in Firefox (Mac).

**Comment by henrinie** [comment]
I can confirm this. After trying to change the language there seems to be some kind of an infinite loop. If I try to change the language once, it doesn't stop even if I try to change the page.

**Comment by vanlummelhuizen** [comment]
After some extensive searching, I think I found the cause of this problem. It comes down to a mismatch between language code for Chinese between Django (zh-hans or zh-hant) and Signbank (cn). To switch between languages, two things are executed (if you are logged in):

- the last_used_language of a user is set to the new language. This done by calling /dictionary/switch_to_language/<language code>
- the page language is changed. This is done by calling /i18n/setlang with the new language code as a POST parameter.

Making Signbank use zh-han(s|t) involves (as far as I can see now):

- Changing the database so that the last_used_language may hold language codes longer than 5 characters
- Changing all language codes cn to zn-han(s|t) in Signbank (could be in quite a number of places).

Note that if you never touch the Chinese flag, no harm is done, in my experience.

**Comment by ocrasborn** [comment]
Thanks @vanlummelhuizen. For whomever will be working on this: we use zh-hans (simplified characters) in the interface, not zh-hant (traditional).

**Comment by Woseseltops** [comment]
Got this working again. I first did the two task suggested by @vanlummelhuizen ('cn' -> 'zh-hans' everywhere on the site) and allowing this longer language code in the database, but it still didn't work. After a long search, I discovered I also needed tot do this:

* Allow longer language codes in switch_to_language url regex.
* Rename the locale folder (with all translations) to zh_Hans (instead of zh-hans, which I tried earlier).

I think this is ready now?
