### ISSUE TITLE
Add buttons to navigate between Detail View, Public View, and Relations View

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#337]
* To facilitate navigation, please add a button at the top of the Detail View and Public View to navigate to the "Relations View".
* On the new Relations View page, add two buttons at the top left to navigate to the Public View and Detail view for that ("source") sign

**Comment by susanodd** [comment]
Please check the bug here, the Public View does not work.
https://signbank.science.ru.nl//dictionary/gloss/85/
This is an example of a sign where the Lemma is different than the Dutch field.
(I am trying to find out where this bug arises, it seems the Public view is generated automatically, but it seems not to work for any of the OPEN, OPEN-C, OPEN-A signs)

**Comment by ocrasborn** [comment]
Ah! Hadn't come across this yet. I've created a separate issue for it, please post any further findings there, @susanodd : https://github.com/Signbank/NGT-signbank/issues/342

**Comment by susanodd** [comment]
Okay, I added the buttons for this.

**Comment by susanodd** [comment]
I haven't figured out how Public View is generated yet, so it hasn't got an extra button yet.

**Comment by susanodd** [comment]
I added the Relations button to the Public View page.

**Comment by susanodd** [comment]
I fixed the Public View button so it works with the OPEN glosses.
