### ISSUE TITLE
Handshapes: add fields (specify handshapes in terms of their distinctive features)

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#345]
* The handshapes that are now one long list can each be specified in terms of a set of sub-features. We want to be able to specify these features for each handshapes, and then search signs by sub-features.
* List of fields:
Finger selection [list of values in field values]
Finger configuration [list of values in field values]
Aperture [list of values in field values]
Thumb [list of values in field values]
Unselected fingers [list of values in field values]
Spreading [list of values in field values]
Finger selection 2 [list of values in field values]
Finger configuration 2 [list of values in field values]
* We will add the values for each of the fields later in Django

**Comment by susanodd** [comment]
At the moment, the user can Search Signs by setting Strong Hand to be Money (for example).
This returns a list of Glosses where Strong Hand is Money (fro example, 155 signs).

Assume the Handshape fields has been implemented (as described above)
and that the fields for Handshape Money (for example) have been set in a new Handshape Detail View for Handshape Money.
(then, for example, assume the above change has been implemented)
Would the new Handshape fields be visible in the Glosses with Strong Hand Money?
Should the Handshape Fields be visible in the Glosses with that Handshape? (probably not?)
Should there be a link in the Phonology panel of the gloss to go to the Handshape Detail view for example Strong Hand Money. (possibly)

**Comment by susanodd** [comment]
The new Handshape Fields would be "per Handshape', rather than "handshape per Gloss".

**Comment by ocrasborn** [comment]
My preference would be to find an economic way of listing the sub-features of each handshape when displaying a sign. (But not when editing it. I mean, we will still keep describing signs in terms of their handshapes by selecting a handshape from the menu, not by selecting subfeatures of handshape.)

**Comment by susanodd** [comment]
(These questions are to help choose the best way to model the data.)

For each of the various field lists, is there a fixed or a variable number of elements?
E.g., Finger selection would be out of 10 fingers.
This could be modelled as each being true or false for each finger, or it could be a list of the selected fingers, with each element being a choice of 10 fingers.

Similarly for Unselected fingers. (Or this could be derived.)

Fingure configuration, are there a set of different choices for each finger?
(As for Selected fingers, which can be boolean, the configuration would be multiple values.)
Do the described specifications (the actual configurations) need to be dynamic (are new configurations introduced, or are there a finite number of possible configurations)
(Is this similar to the choice lists for phonology fields, or is it more like the keywords entry?)

For the field lists that are e.g. based on fingers (10), it could be shown with each finger as a pull-down menu of choices for that finger.
Are there images associated to the configurations? Or drawings? This could be displayed in the Gloss Detail view.

**Comment by susanodd** [comment]
Aaaah, that ought to be 5 fingers.

**Comment by susanodd** [comment]
Or 4 fingers and a Thumb.

**Comment by susanodd** [comment]
Okay, hmmm.
www.ru.nl/publish/pages/514513/vanderkooij1998_lin_usf.pdf

**Comment by susanodd** [comment]
http://clml.uchicago.edu/~jkeane/sll/Papers/Brentari-Companion%20to%20Phonology%20(chapter%20Handshape%20in%20Sign%20Language%20Phonology)%20(2011).pdf

**Comment by susanodd** [comment]
Okay, it seems wise to make each field list be a choice menu
And to use a particular number of fields per each field list
So in the database record for a particular handshape, there will be fields for e.g. the finger configuration of each finger. These can then all be displayed in a row called Finger configuration.
I'll make something that shows what I think you mean.

**Comment by ocrasborn** [comment]
Yes, selection of fingers has a rather specific list of values, not simple a number from 1-10, and it's language-specific. Configuration is less language-specific, but you may have already found in these two papers that different researchers have different takes on this. That's why I ask for a listing in Django's field values, so that we can specify and modify the values ourselves.

**Comment by susanodd** [comment]
http://www.journal-labphon.org/articles/10.5334/labphon.45/

**Comment by susanodd** [comment]
Okay, I started making "example data" so there can be a starting point. Then the actual values can be changed and tweaked in the database. (The actual lists of field values.)
(It's a bit chicken or egg.)
To start, I'm making it be:
finger_selection_index, finger_selection_middle, finger_selection_ring, finger_selection_pinkie, finger_selection_thumb
And for each one of those (together the list of finger selection)
Using the Joint configuration examples of the 2nd pub:
Fully open, Bent, Flat-open, Flat-closed, Curved open, Curved closed, Fully closed
For Spreading, I found: Plain, Spread, Stacked, Crossed
For Aperature, I found: Open, Closed

(Some initial values for field choices, since the database needs example data to code on top of.)

**Comment by ocrasborn** [comment]
That's a good start Susan, thanks

**Comment by ocrasborn** [comment]
Hi @susanodd , I've added two fields in the first comment above: "finger selection 2" and "finger configuration 2". I had forgotten about the need to include these, but there are cases where there are two sets of selected fingers with different properties. You can copy the initial values from what you proposed for the other fields for Finger Selection and Finger Configuration.

**Comment by susanodd** [comment]
A question about Finger Selection. I've made it so that there are 5 finger selection fields.
In the database there are e.g., Finger Selection 1: Thumb, Finger Selection 1: Index, Finger Selection 1: Middle, Finger Selection 1: Ring, FInger Selection 1: Pinky
So Finger Selection 1 is a list of 5 things, each of which is a choice.
I put Plus and Minus as choices to start.
This seemed logical as a first step to assume that fingers can be either selected or not selected.
But since that might not be the case, it's implemented as a choice list rather than a boolean (checkbox).

The question is, could this be a boolean instead? It would make the display look better. I'll post a screenshot to show what it looks like at the moment.

**Comment by susanodd** [comment]
![handshape-view](https://user-images.githubusercontent.com/24272544/27830930-df75ac96-60c8-11e7-847b-499f73cdf355.png)
![handshape-view-2](https://user-images.githubusercontent.com/24272544/27830936-e3e91cf4-60c8-11e7-8fd4-bf9bfdeed167.png)

**Comment by susanodd** [comment]
I made the finger selection choices be Plus and Minus but if these are just boolean values, as well as Unselected Fingers, then a more economical display would be better.

**Comment by ocrasborn** [comment]
Hi @susanodd , nice to see this coming about! The specification per finger is more complex than we need though, and thus also more complex than necessary for entering data. We'd prefer to specify the fields Finger Selection and Finger Configuration with a single string, like "TIM" for thumb + index + middle being selected. A single configuration feature applies to this finger selection, so it would suffice to have a single string there as well: "curved", "clawed", "hooked", for example. The "Finger Selection 2" caters for the rare handshapes where some fingers are in a different configuration. So all fields can be string values, which we can later alter/extend in Django if needed.

**Comment by susanodd** [comment]
I modified the finger selections to be the TIM patterns.
I did it as a choice list rather than as a string to keep the data normalised. The choices can be modified in the admin page for Field choices.
I'm assuming there will need to be query facilities to find handshapes using the Thumb, etc.
I'm going to work on the List view of handshapes to see if more tweaking is needed.

![handshape-detail](https://user-images.githubusercontent.com/24272544/27862157-3f10c990-6184-11e7-908a-9090b103ea08.png)

**Comment by ocrasborn** [comment]
Excellent! Yes, that's what I actually meant with 'string', a list of choices, sorry for the confusion.

**Comment by ocrasborn** [comment]
Oh, one more thing, or two actually:
1. The field 'aperture dynamic' can be left out: we already have this encoded in 'handshape change' for each gloss, and we could also choose to include complex values to encode this (like 'open > closed')
2. What I forgot altogether: we will like to upload an image of each handshape, displayed and editable in this detail view, and also in a list view of handshapes (much like the image on the left of the glosses in the list view).

**Comment by susanodd** [comment]
![handshape_with_image](https://user-images.githubusercontent.com/24272544/27958305-b87dd06c-6322-11e7-90ea-4a796ccbaa87.png)
![handshape_view_edit](https://user-images.githubusercontent.com/24272544/27958308-bc8d679e-6322-11e7-8a20-149507dd7b22.png)

**Comment by ocrasborn** [comment]
Looks good to me!
