### ISSUE TITLE
Handshapes: search signs by handshape features

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#348]
* Expand present search form for phonology by adding the handshape fields

**Comment by susanodd** [comment]
![search-handshapes](https://user-images.githubusercontent.com/24272544/28015660-335b5f66-6571-11e7-8653-fc57cccca8b0.png)

**Comment by susanodd** [comment]
Querying is working now. I'll get the fields in the results adjusted to show all fields.
I have the page so that you can select Search handshape, or "pull-down" to Search sign.
(I didn't do Search sign yet.)
So we want to search for signs that use the (found) handshape(s)?
I made this search form be for Handshapes (it's basically  the List View of Handshapes, with Query functionality.)
So then I need to also adjust the Search sign query to include fields for Handshapes. (Yes, that's what this issue says.)
I guess multiple types can't be in the same query result list. So searching for signs as part of the page shown above probably doesn't make sense. Oh wait, I guess it would be a list of signs instead.
I am wondering if the user would want to search of "part of" the Finger selection?
(So say for Thumb and Index. Rather than TI.)
[Does that make sense to be able to search for a subset of Selected Fingers? That was that Boolean for Each Finger modelling of this field. I can convert back and forth to the choice list.]

**Comment by ocrasborn** [comment]
Yes, we want both to search for handshapes, and to search for signs by handshape features.
Now we're at it, it would be good to think about a way to make this search more flexible than to select one out of all values for a field. In case the number of values is limited (say, 1-15), something with checkboxes to select one or multiple values could be good. Alternatively, we could use regular expressions (as in the gloss searches), and have help popups listing the values. Could you discuss this with @vanlummelhuizen ?

**Comment by ocrasborn** [comment]
Don't think I understand your question about searching for "part of", could you explain?

**Comment by susanodd** [comment]
I have a field Number of selected fingers (Quantity) because one of the papers I looked at to see how they modelled handshapes had used Quantity. I changed it say quantity to fit better in the results list. I'll delete this if it's not needed.

**Comment by susanodd** [comment]
![handshape-query-2](https://user-images.githubusercontent.com/24272544/28019812-84dc4470-6582-11e7-866d-900f2e9def7b.png)

**Comment by susanodd** [comment]
There is no Dutch translation for Handshape since it's either Strong or Weak hand.
The Handshape column (see screenshot) is what it is in the language being used.

**Comment by susanodd** [comment]
Hmmm. I just noticed that it's either Strong hand or Weak hand having a particular Handshape (as the Query facility is currently implemented for Signs.) So we probably want it to be either? (Either Strong hand or Weak hand matches Handshapes with the requested fields.)

**Comment by ocrasborn** [comment]
I think we'd want to be flexible here: by default searches should search for either hand, but a checkmark or something should enable "Only strong hand" and "Only weak hand". I know I know, I keep making up requirements as you go :-)
As for the "Number of selected fingers", I actually quite like adding that! It's not strictly speaking a phonological concept, but it will come in handy for all kinds of questions I expect. Thanks!
The Dutch term for "Handshape" is "Handvorm" (Sterke hand, zwakke hand); but we'll have to do another run of translations soon anyway, so please add {% trans %} tags as much as possible.

**Comment by susanodd** [comment]
![handshape-query-fingers](https://user-images.githubusercontent.com/24272544/28068670-ce6c0f70-6646-11e7-83c9-665e3dd3f15c.png)

**Comment by susanodd** [comment]
I had to zoom out so it would fit. In this example, I made it so the finger selection can be per finger.
I'm making it so that when editing a handshape, you can edit each fingers of the Finger selection.
But when displaying the handshape, it uses the abbreviated forms TIMRP, TIM, etc.
I had to add the choice Either, so it can match selected and not selected. (Choosing Eitther removes the finger selection for that finger from the query so it will match anything for that finger. To get partial matches.)

**Comment by ocrasborn** [comment]
That looks quite doable, thanks for that, but you were also talking about searching for an exact number of fingers, no? Like in, "one SF but it doesn't matter which". That might come in handy, and it would be fine if we'd need to specify this number explicitly in a field, there's only so many handshapes to describe.

**Comment by susanodd** [comment]
Yes! The Quantity would be useful for that. (It can be computed from the finger selection if it's not set.)
I'm also working on querying the signs based on the handshape fields.

**Comment by ocrasborn** [comment]
oh right! I missed it, sorry

**Comment by vanlummelhuizen** [comment]
@susanodd @ocrasborn This is live now! #345 #346 #347

**Comment by susanodd** [comment]
https://signbank.science.ru.nl/dictionary/handshapes/

**Comment by ocrasborn** [comment]
@susanodd , could you set the default number of search hits that are displayed to 50 rather than 5?

**Comment by ocrasborn** [comment]
Great to see this live now, btw!

**Comment by susanodd** [comment]
Fixed. (Pushed to github master branch.)
