### ISSUE TITLE
Add search field for Lemma ID Gloss

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#353]
* As we didn't use the lemma gloss actively until now, we never felt the need before, but now I'm really surprised we didn't add it before :-) 
* If it fits on one row with the translation equivalents (by making the type-in fields ±1/3rd smaller), that's be best; in that case, add the lemma gloss after the Dutch/English glosses.
* Proposal for layout, if it doesn't fit in one row with the translation equivalent search box: two rows; on the first, the two Annotation ID gloss fields (Dutch/English), with these labels (Annotation ID Gloss: Dutch; Annotation ID Gloss: English). On the second row, first the translation equivalents, then the "Lemma ID Gloss".

**Comment by susanodd** [comment]
The way the search functionality is implemented at the moment is that the Dutch Gloss matches either the Dutch Gloss or the Lemma Gloss.
Shall I make it so that the Dutch field is only the Dutch Gloss and the new Lemma field is the Lemma?
I'm guessing the Dutch Gloss search field was previously made to be "either" because otherwise some stuff wouldn't be found otherwise.

I've made the search field for Lemma be "exact" rather than a regex.
An example Lemma that I know of is Open, where the variants all refer to the Lemma.

In order to find Open instead of everything with "open" as a substring, it has to be an exact match.
I'll add a column for the Lemma in the results.

**Comment by susanodd** [comment]
Okay, this is fixed now. It uses the same regex pattern matching as for Dutch.
And the Dutch search field now only looks at the Dutch field.

**Comment by ocrasborn** [comment]
:-)
