### ISSUE TITLE
Install SVN on Yale server

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#363]

**Comment by Woseseltops** [comment]
This was harder than expected, because I lost the ability to install stuff during a hardware upgrade. Kraig fixed it for me, and now I have been able to run 'sudo yum install subversion' successfully. 

What's next, @ocrasborn ? Shall I look up how to create an SVN repository? Or maybe create SSH-accounts so everyone can access? Do note that the server is only reachable if you're on the Yale campus, or via a VPN, for which you need Yale credentials.

**Comment by vanlummelhuizen** [comment]
Perhaps SVN over HTTPS could make the SVN server accessible from outside the Yale network.

**Comment by Woseseltops** [comment]
Indeed @vanlummelhuizen , I came to the same conclusion in a private mail thread with Onno :).

**Comment by Woseseltops** [comment]
( note to self: i was working on getting things working with https://tecadmin.net/setup-subversion-server-on-centos/ )

**Comment by Woseseltops** [comment]
Okay it take a lot of time, but I figured it out! We can now do SVN over the HTTPS port 443, meaning no VPNs or Yale accounts: I've been able to both read (checkout) and write (commit) without VPN, using an account I created myself. Let's document some things:

* You need to checkout (= git clone) like this `svn co https://aslsignbank.haskins.yale.edu/svn/myproject` .
* HTTP account need to be created on the server like this `htpasswd -m /etc/svn-users user1`
* SVN repos can be added to `/var/www/repo` (with command `svnadmin create myrepo`) and need to readable and writable by the user apache.

What's next, @ocrasborn ?

**Comment by ocrasborn** [comment]
Please create a test-repo named slaaash (yes, 3 vowels), where we can put some EAFs so you can make sure the scripts run on this repo.

**Comment by ocrasborn** [comment]
Great that you've got it working by the way!!

**Comment by Woseseltops** [comment]
Done, @ocrasborn !
