### ISSUE TITLE
Install scripts on Yale server

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#364]

**Comment by ocrasborn** [comment]
Check with Micha whether they need modification to match the ASL EAFs

**Comment by ocrasborn** [comment]
* Update ECV from Signbank 
* Update EAFs on the basis of the ECV
* Frequencies update script need not be installed for ASL for the moment
* Make sure they run overnight, US Eastern time zone

**Comment by Woseseltops** [comment]
I figured out what all of these scripts were exactly. For later reference:

|Functionality|Where to be found|Working in ASL Signbank?|
|-|-|-|
|Update ECV from Signbank (= #278 )|https://aslsignbank.haskins.yale.edu/dictionary/update_ecv/|No|
|Update EAFs on the basis of the ECV|/home/ocrasborn/corpusEcvUpdater (non-tracked code by Micha)|No|
|Frequencies update script|https://signbank.science.ru.nl/dictionary/update_cngt_counts/|Not needed|

**Comment by Woseseltops** [comment]
Verified that the update ECV functionality is working now. Next up is the EAF, might need Micha for that.

**Comment by Woseseltops** [comment]
Update:

|Functionality|Where to be found|Working in ASL Signbank?|
|-|-|-|
|Frequencies update script|https://signbank.science.ru.nl/dictionary/update_cngt_counts/|Not needed|
|Update ECV from Signbank (= #278 )|https://aslsignbank.haskins.yale.edu/dictionary/update_ecv/|Yes|
|Update EAFs on the basis of the ECV|/home/ocrasborn/corpusEcvUpdater (non-tracked code by Micha)|In progress|

Okay I investigated what this last script does, and apparently it makes updates to the corpus-ngt svn repo. I imagine that the Americans don't want to make updates to an svn repo, but to an asl repo, right? And this also means that this task is dependent on #363 , right?

**Comment by ocrasborn** [comment]
Right!

**Comment by Woseseltops** [comment]
Summary for myself about the EAF task (because I kept getting confused about it): an EAF is a file where ELAN stores annotations. Inside this EAF are references to an ECV, and these references might need to be updated. The 'corpusECVUpdate' code gets a folder of EAFS as input, looks which ECV they use,  updates the EAF files if needed and finally commits the result to a repository. This repositiory is the corpus-ngt repository for the Dutch variant, but a test repository named 'slaaash' for the American variant, containing two test EAFs put there by Onno.

Progress for the EAF script task:
* All code moved to the Yale server
* Successfully installed java 8
* Changed all paths inside the updater script, and changed the URL of the repository

To do: make it a recurring thing.

Not sure though if the script is doing what it should be doing, will send output to Onno.

**Comment by Woseseltops** [comment]
Script looks okay, made it a recurring thing. Please keep this issue open so I remember to check if it's working.

**Comment by Woseseltops** [comment]
Okay, apparently I forgot to actually log any results. Did that now, will check if it's working next time.

**Comment by Woseseltops** [comment]
As far as I can tell, the logs are looking good, so I'm closing this one.
