### ISSUE TITLE
Special character in gloss leads to error in naming media file

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#366]
Or so it seems, see screen shot. I think we noticed this before and used the simple work-around of not including special characters in glosses, but that is silly: we want to be able to use any character used in the orthography of the spoken language.
![screenshot 2017-08-16 14 24 09](https://user-images.githubusercontent.com/10242207/29363098-e48307b4-828e-11e7-9df3-dc792c3ac25c.png)

**Comment by ocrasborn** [comment]
Possibly related to #306

**Comment by Woseseltops** [comment]
I've had a detailed look, and it seems like we lost support for special chars in media names when we put them behind authentication. What happens is that:
1. The request is first sent to a Django view, as if it were a normal page.
2. When Django thinks it's okay (authentication okay, file exists, etc), it sends back a normal but empty webpage, with one extra header 'X-Sendfile' that contains a path to the file to be displayed.
3. Apache has been configured by us to use 'X-Sendfile', which I think basically tells Apache: 'if you see this header, don't display the page, but go look for the file'. 

I've been able to confirm that step 1 and 2 can handle the special char. It seems to go wrong in the very last part of step 3: 'go look for the file'.

I have a number of ideas on how to fix this, but I don't rule out the possibility that we won't succeed in fixing this, because we are dependent on the X-Sendfile module.

**Comment by Woseseltops** [comment]
Some findings:
* This question, exactly our situation, seems to suggest we just need an update of Xsendfile: https://stackoverflow.com/questions/9288203/using-x-sendfile-with-utf-8-files-without-updating-my-files-or-database
* Indeed, non-ascii support seems to have been added in this commit: https://stackoverflow.com/questions/9288203/using-x-sendfile-with-utf-8-files-without-updating-my-files-or-database
* We downloaded our version from the website, which seems to be release v0.12, 3 commits earlier. 


I feel like a detective now :) . Will write C&CZ next week.

**Comment by susanodd** [comment]
I had a similar problem with Handshapes images. So I just gave the uploaded file the numerical value as a filename (machine_value). If there is an image for a Handshape, there is only one image.

**Comment by Woseseltops** [comment]
> Will write C&CZ next week.

No response yet, will try again next Monday (they don't respond well on Fridays).

**Comment by Woseseltops** [comment]
I was so busy with the ASL Sigbank, I never let you guys know this works again! Happy @ocrasborn ?
