### ISSUE TITLE
Dataset 'Main' should automatically be assigned to new glosses in ASL SB

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#390]
It seems that the Dataset functionality for the Dutch system has broken something for the ASL system:  new signs since a certain date do not get the dataset 'Main' assigned automatically, and are invisible to searches (or rather: they are not included in anything displayed through the list template). It seems as if dataset 'Main' was assigned batch-wise to existing glosses, but not yet to any new gloss. Result is in the behaviour described below by Julie:

----------
When we're adding new glosses to ASL Signbank, they're found in either "recently added signs" or "proposed new signs" - my annotators reported that they could not find them again via search (for the glosses they entered or translation equivalents). Search fails for me too. I vaguely remember you asking me if we wanted to implement a feature (protocol? what's the best word?) where I'd get a list of the signs to approve via email. Is this related to that? If so, please let me know how to move on to the next steps so I can get the ID glosses in the system. 

Also, after I approve the signs (by finding them through the lists), they're not showing up in the full lists either even after I tick off the box "proposed new sign". Some examples: COVER-UP, SUNLIGHT, FORTY-FIVE, FIVE-WEEKS

**Comment by Woseseltops** [comment]
Good find @ocrasborn ! The problem Julie describes is indeed caused by the fact that new signs get no default dataset. NGT most likely also had this problem until commit 7b3b5b536, which Micha put live an hour ago or so; it adds that you can select one during creation. 

On the ASL branch (which always a few weeks behind as requested by Lee) I have created an temporary construction with a new setting DEFAULT_DATASET_PK . For the real solution: @vanlummelhuizen , shall we make it so that the dataset selection screen does not show up if DEFAULT_DATASET_PK is set?

**Comment by Woseseltops** [comment]
Note: I've also added the default dataset to signs without a dataset, so you can use everything in search again :).
