### ISSUE TITLE
Add Google Analytics tracker

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/NGT-signbank#399]
Details in Wessel's mailbox.

**Comment by Woseseltops** [comment]
Done, accidentally gave commit a382ef3 the wrong number. Does it work @ocrasborn ?

As a side note, I'm conflicted about Google Analytics. On the one hand, I really like the idea of collecting statistics on everything, so if have some ideas on how Signbank is used we have the data to verify or debunk these. Google Analytics is probably still the best tool for this.

On the other hand, see https://en.wikipedia.org/wiki/Google_Analytics#Privacy ; maybe Signbank users will soon see sign language related ads everywhere :) .

**Comment by henrinie** [comment]
We are preparing to start using Piwik for this. You can run it yourself and it won't leak your user data to Google. We have opted out of Google analytics due to privacy issues and reasons, we don't want to give all of our user data to Google for free. The users won't even be aware of this.

The tool itself is good though.

**Comment by ocrasborn** [comment]
It works @Woseseltops , thanks.
I've used Piwik before myself, was quite happy with what it gave back to me about frequency of use. I'll make it a low-priority issue to consider Piwik or another alternative, and close this for now.
