### ISSUE TITLE
Add complex fields to CSV export-import routines

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#42]
- Morphology
- Relations to other signs
- Relation to foreign signs

Perhaps as one semi-colon separated list? For example category1: value1; category2: value2; category3: value3

**Comment by susanodd** [comment]
Okay, since I was busy with the CSV for etymology, I started on this issue.
I've done as proposed for Relations to other signs and Relation to foreign signs.
(See screenshots.)
For Morphology, there is Sequential and Simultaneous.
How would you like the categories to look for these?

![csv-export-relations-1](https://user-images.githubusercontent.com/24272544/30212085-a858ed4a-94a3-11e7-8a71-dfebcaf5168f.png)
![csv-export-relations-2](https://user-images.githubusercontent.com/24272544/30212088-ac471cd8-94a3-11e7-8dac-277e56c30b30.png)

**Comment by susanodd** [comment]
I had to use a comma to separate cat:val pairs rather than a semicolon, or OpenOffice puts the items in separate cells.

**Comment by susanodd** [comment]
If the wish is to be able to also import the format, then additional information may need to be saved to the cat:val data. (Loan word for the Relation to foreign signs.)

**Comment by ocrasborn** [comment]
* Yes, it would be good to also have the binary field 'Loan word' in the export (and import).
* For Sequential and Simultaneous Morphology, two columns would be needed.
* For sequential morphology, the glosses could simply be listed in the order in which they are specified (first Compound Part 1, then Compound Part 2; without explicitly listing this property).
* Would it be an idea for Simultaneous Morphology and Relations to Foreign Signs to use some sort of brackets to group the values for each field, so we have one grouped value for each row? Like in the top screen shot above, {False,English,CUCUMBER},{True,English,HAPPY}? Or will spreadsheets (we use LibreOffice for this) assign a special function to the curly bracket? I'm fine with any marker, angled brackets, regular brackets, curly brackets, hash symbol, caret, whatever.

**Comment by susanodd** [comment]
It's easier to separate the elements in the cell using the comma, and to use a colon to separate the tuple entities.
So to add the Loan word tag, the above could be False:English:CUCUMBER, True:English:HAPPY

It's straightforward in python to use and identify the comma as a separator inside the cell.
(This can be done with the split function.)
And again for each of those elements, again use the split function on the colon.

Otherwise there needs to be more involved parsing. (Because of opening and closing brackets.)

I'm adding checks on the complex values to allow testing for the existance of the new things when the list of proposed changes is displayed. (Rather than cause errors during an attempted update.)

So far, I've added this to Dialect and Sign Language (which are actually also complex as is Keywords.)

**Comment by susanodd** [comment]
So I've got the Relation to foreign signs working (version 0.1).
In this data (in the database), the fields are loan_word, other_lang, other_lang_gloss.
The loan_word is a Boolean (can't be null, default is false)
The other_lang and the other_lang_gloss are both strings.
The table for Relation to foreign signs stores "relation ids" for the relations that have been stored. Each of these has a gloss (gloss id). That is how the "relation" is implemented.
I've made it so that for all the "relations to foreign signs" found for a gloss, the "new" data routine checks the "other_lang_gloss" field to see if that relation already exists and should be updated. (e.g., for the gloss (row in the CSV), for an already existing "relation to foreign sign" to "other_lang_gloss", then the other fields will be updated. (e.g., you can change the loan_word setting or the other_lang setting for that relation to foreign sign other_lang_gloss.)

(The loan_word and the other_lang are attributes and the relation is between the gloss and the other_lang_gloss. Although the other_lang_gloss is a string.)

It's not entirely clear if these "other_lang_gloss" are meant to be strings, or if they are meant to be actual glosses in a different language. They're just strings rather than object ids (or foreign keys).

I'm going to leave them as strings, as they are. But just thought to mention the way this table is set up.

**Comment by susanodd** [comment]
![csv-import-complex-values-morphology-1](https://user-images.githubusercontent.com/24272544/30861948-a4e4431c-a2cc-11e7-8e72-f51fef608d06.png)
![csv-import-complex-values-morphology-2](https://user-images.githubusercontent.com/24272544/30861953-ab0fcbc6-a2cc-11e7-93f7-b4ea1f24f2fa.png)
![csv-import-complex-values-morphology-spreadsheet](https://user-images.githubusercontent.com/24272544/30861959-aeaafdfa-a2cc-11e7-8c28-d149318955ff.png)

**Comment by susanodd** [comment]
I added the complex values for the morphology. Morphology is now in two columns. (Also for export.)
The values in a cell are separated by comma's. And if those values are complex, the parts are separated by a colon like the relations.
I added checks on the existance of glosses and morphemes in the import file. The errors are printed on the changes summary, so the user can check these before trying the command.

**Comment by susanodd** [comment]
The ordering for the morphology is retained. So it's what the user specifies in the CSV.
I made it so the old (object) relations are deleted and the new are created. This way to make sure the ordering is that specified.
For the relations to (foreign/other) signs, the ordering is by the other gloss. The code sorts the new relations data for comparison to the existing data. This way to prevent loops of attempting to add the same values in a different order.
The keywords (and morphology) are ordered in the order the user has entered them.

**Comment by susanodd** [comment]
Oh, I see I need to check that for Foreign Relations.

**Comment by susanodd** [comment]
For the relations, the ordering is behind the scenes. The Gloss Detail View is still the same as it was.

**Comment by ocrasborn** [comment]
Hi @susanodd , the screen shots look good to me except for one thing: the sequential morphology should show the gloss in the second column (and in the CSV), not a phonological value of some sort.

**Comment by ocrasborn** [comment]
:-)

**Comment by susanodd** [comment]
Here is a summary of the error checking done on the complex values fields.
Error messages are shown and the user needs to fix these in the CSV file before it can be imported.
As in Issue #370 the duplicates are ignored, except forne.g., the Sequential Morphology, this might be a sequence? (See question marks below.)

Error checking Import CSV

(WARNING) Duplicate Dialect value
(ERROR)   Non-existent Dialect value

(WARNING) Duplicate Sign Language value
(ERROR)   Non-existent Sign Language value

(ERROR)   Non-existent Sequential Morphology Gloss
(WARNING) Duplicate Sequential Morphology value (?)
(ERROR)   Too many component Sequential Morphology Gloss values

(ERROR)   Syntax error Simultaneous Morphology, comma-separated morpheme:role sequence expected.
(ERROR)   Non-existent Simultaneous Morphology Morpheme
(ERROR)   Simultaneous Morphology Gloss is not a Morpheme (?)
(WARNING) Duplicate Simultaneous Morphology value (?)

(ERROR)   Syntax error Other Relations, comma-separated role:gloss sequence expected.
*** Duplicate values silently removed ***
(ERROR)   Non-existent Other Relations value Role not found.
(ERROR)   Non-existent Other Relations value Gloss not found.

(ERROR)   Syntax error Foreign Relations, comma-separated bool:string:string sequence expected.
*** bool value must be in false, False, true, True ***
*** Duplicate values silently removed ***

**Comment by ocrasborn** [comment]
I think we were about to close this, @susanodd , but could you still add 'blend morphology' to the CSV export for me? (It doesn't occur very often, so I bet we won't be changing-and-then-importing it, so you can leave it out of the import routine.)

**Comment by susanodd** [comment]
Blends have been added to CSV export.
