### ISSUE TITLE
Searching for videos in Django admin doesn't work

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#59]
![screenshot 2015-05-18 13 15 58](https://cloud.githubusercontent.com/assets/10242207/7679750/1809e046-fd60-11e4-9e1a-020cfb45cf3a.png)

**Comment by Woseseltops** [comment]
Before I fix this: are you aware that these GlossVideo models you want to search are rarely used by Signbank, @ocrasborn ? For example, the video you see on the gloss detail page is just there because the page checks if there is a video file that matches the gloss name and id, and ignores the GlossVideo model completely. I think they are only created when you upload a new video on the gloss detail page.

**Comment by ocrasborn** [comment]
Hm, hadn't realised that, no. OK, let's not spend time on this now, then.
