### ISSUE TITLE
Create a 'Cancel' button next to the Save button in edit mode

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#64]
And at the same time, move the 'Delete Sign' button to the left, at the same height (it's not used very often, and now more easily leads to mistaken deletions)

**Comment by Woseseltops** [comment]
I've looked into how this would work, and wanted to let you know that this will be more complicated / time-consuming than you'd probably expect. This is because:
* The 'save' button is no real save button; it only toggles edit mode. 'Turn off edit mode' would be a better name.
* The real save button is the 'OK' button that appears when you're editing a field. You can verify this by making a change, hitting 'OK', and then refreshing the page. See? The change was already saved to the database, although you didn't press 'Save' yet.

Proposal for change:
* Change the text 'Save' to 'Turn off edit mode'
* Add an extra button 'Rewind changes'. For this button, the browser will need to keep track of all things that are changed, and 'play' them in reverse order when this button is pressed.

**Comment by ocrasborn** [comment]
Agree, good idea.

**Comment by Woseseltops** [comment]
I've spent several hours on this now already, and it hurts my head. Summary of my findings and achievements so far (mainly for myself, for when I continue on this):
* The fields are made editable with plugin called Jeditable. 
* With Jeditable, the only way to do something extra when the user clicks 'OK' is to use the callback function.
* In the callback, once a user changed a value, there seems no way to retrieve what the original value was except to return it with the answer to the POST. The old and the new value are separated with a comma here, and the Javascript that receives them splits them again.
* All changes to dropdown menus are now saved in browser memory, using the functionality described above.

To do:
* Make this work for other types.
* Add the actual rewind function.

**Comment by Woseseltops** [comment]
Another note for myself: to rewind, multiple button presses need to be simulated by doing the accompanying POST requests. However, when more than one field has to rewound, and thus multiple simultaneous POST requests need to be done, only the last POST request seems to be handled by Django. Delaying the requests did not work so far, because then Javascript sends along only the latest data.

**Comment by Woseseltops** [comment]
I've got the most important part of the functionality working now for the dropdown menus and text fields. The end is still not in sight, though, because of a numbe of corner cases:

* When a field goes from '-' to something, and you rewind, it does not work (text) or you get 'None' (dropdown menus).
* Rewinding does not work yet for defining keywords and selecting checkboxes.
* Selecting languages and some checkboxes now leads to an error.
* The whole thing does not work for things that use separate database tables, like relations to other signs, morphology, etc. If we want to be able to rewind these as well, a whole lot of extra code needs to be written.

@ocrasborn, to help you prioritize: I've now spent around 8 hours on this, and my expectation that it will be another 4-8 hours. That is, from a developer perspective, this is a huge and hard feature.

**Comment by ocrasborn** [comment]
@Woseseltops: I see. Let's park this feature for some time now then, and move it to a later project, by removing the button altogether so that users don't get errors or in-complete functioning, and then we'll take it up some time next year.

**Comment by Woseseltops** [comment]
Done. The functionality (change tracking etc) is still there, but the users won't see it.

**Comment by Woseseltops** [comment]
Note to myself: I turned off saving edits for text, because the character separating the old and new value in the POST response clashed with the comma character separating keywords (in the translation equivalents).

**Comment by ocrasborn** [comment]
@Woseseltops , is there anything left to do here?

**Comment by Woseseltops** [comment]
Yes we decided that I stop working on this because it turned out to be harder than we thought:

>  Let's park this feature for some time now then, and move it to a later project
