### ISSUE TITLE
Make sure all database relations are maintained when changing the field idgloss

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#65]
* Change the file name of the linked video files when an Annotation ID Gloss is changed
* You get an error if the idgloss and the idgloss_dutch don't match, so you should always change them both
* When you change the idgloss, the page incorrectly shows 'old_value,new_value' instead of just 'new_value'

**Comment by Woseseltops** [comment]
While investigating this problem, I've encountered some other problems as well:
* You get an error if the idgloss and the idgloss_dutch don't match, so you should always change them both.
* When you change the idgloss, the page incorrectly shows 'old_value,new_value' instead of just 'new_value'.

Two questions:
* How do we want to solve the first problem?
* Maybe we can rename this issue: keep links when changing id gloss, with these three sub problems?

**Comment by ocrasborn** [comment]
1) idgloss and idgloss_dutch should be allowed to be different: we want to use idgloss as the lemma, which can link multiple annotation id glosses ('full forms', inflections, etc.). Right now we haven't actually entered more than one full form per lemma, and so the values for the two fields happen to be identical at the moment for all entries.
2) OK

**Comment by henrinie** [comment]
I tried to come around the filename issue with this commit:
https://bitbucket.org/heilniem/signbank-fi/commits/3a3f99c2566e04963f7c9292db1c0abe3855ba57

Not the best way, and should probably be made reusable too.

**Comment by Woseseltops** [comment]
Fixed:
* When you change the idgloss, the page incorrectly shows 'old_value,new_value' instead of just 'new_value'

To do:
* Change the file name of the linked video files when an Annotation ID Gloss is changed
* You get an error if the idgloss and the idgloss_dutch don't match, so you should always change them both

**Comment by ocrasborn** [comment]
There currently is an entry with an empty Annotation ID Gloss: Dutch, and the Annotation ID Gloss: English is "MOVIE-B"; this can't be edited without leading to an error. Wessel, can you a) remove it, and b) enforce that entries cannot have an empty ID Gloss: Dutch in the future? The English ID Gloss should be allowed to be empty, as this is often added later.

**Comment by Woseseltops** [comment]
Fixed: You get an error if the idgloss and the idgloss_dutch don't match, so you should always change them both

Todo: Change the file name of the linked video files when an Annotation ID Gloss is changed

**Comment by Woseseltops** [comment]
>  Wessel, can you a) remove it

No, apparently, because I cannot find it. Did you perhaps remove it already?

> enforce that entries cannot have an empty ID Gloss: Dutch in the future?

Okido, although I feel like that might be worth its own issue.

**Comment by Woseseltops** [comment]
Did the video part as well. I have a feeling I forgot about some corner cases though, so let me know if you walk into problems/errors.

**Comment by ocrasborn** [comment]
I can still find the English gloss MOVIE-B, simply by using the search field

**Comment by Woseseltops** [comment]
Ah, now I have it; I had to use the English field . Removed it by clicking 'delete' in the admin ;).

**Comment by Woseseltops** [comment]
The videos still give an error when the idgloss is changed.

**Comment by Woseseltops** [comment]
Fixed. The problem was that Signbank tried to change the name of the onnotest gloss, but found nothing (because there was no video for onnogloss).

**Comment by henrinie** [comment]
I had some problems on Finnish signbank when changing the filename.
I was not catching ObjectDoesNotExist when changing filename (which happens when you change the gloss name), resulted in an error when we tried to change the name for a gloss that had no video.
**The bigger problem I noticed:**
We were not changing the filenames for the reversion files when changing gloss name. I mean the files that are stored when you upload another video for a gloss (glossname-id.mp4.bak.bak.bak etc).

**I am not sure if you have these problems or not, but I suggest that you at least check if you have these**
You can see my solutions at https://bitbucket.org/heilniem/signbank-fi/commits/2bf229dd256b (Please comment if you see anything weird in that)

**Comment by richardbank** [comment]
When changing an ID-gloss, a video with the new name is created, but the old one is not deleted. The old video should be removed.
Example: \
old gloss: BETRAPT; video BETRAPT-3043.mp4
new gloss: BETRAPPEN; videos BETRAPPEN-3043.mp4 and BETRAPT-3043.mp4

**Comment by henrinie** [comment]
It looks like it is intentional that the file is not deleted because it is just copied here:
https://github.com/Signbank/NGT-signbank/blob/master/signbank/dictionary/update.py#L207

It could fixed by adding a line that deletes the old location (if the copy was successful).

**Comment by Woseseltops** [comment]
@henrinie is correct, the file was copied instead of renamed. This was probably because I was afraid to throw away videos with a feature I was not 100% sure worked correctly. Also, the gloss private key was also still in the name of the video, so it's not like videos could be mixed up. Still, it's better to rename because of disk space, so I changed it now :).

**Comment by ocrasborn** [comment]
Does that complete this issue, @Woseseltops ?

**Comment by Woseseltops** [comment]
I think so, yes :)
