### ISSUE TITLE
Enforce that Annotation ID Gloss & Annotation ID Gloss: English each contain unique values

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#76]

**Comment by henrinie** [comment]
https://github.com/Woseseltops/signbank/blob/master/signbank/dictionary/models.py#L772
and
https://github.com/Woseseltops/signbank/blob/master/signbank/dictionary/models.py#L785
--> Add unique=True, I think that should fix your problem, it needs a migration though.

**Comment by Woseseltops** [comment]
Partly done: you can no longer add new glosses that have an 'Annotation ID Gloss' or an 'Annotation ID Gloss: English' that is already in the database.

However, before I force this in the database structure, as @henrinie suggested (thanks :) ), I need to make sure the things in the database right now are also unique. This is not the case for Annotation ID Gloss: English:
* RING is found at both AANBELLEN and RING
* SOON is found at both BINNENKORT and STRAKS
* BLOW is found at both BLOWEN and PIJPEN
* FAINT is found at both FLAUWVALLEN and VAAG
* QUICK-C is found at both GAUW and SNEL-C
* HEARING-AID is found at both GEHOORAPPARAAT and GEHOORAPPARAAT-B
* QUICK-B found at both SNEL-B and SNEL-D

And these all have an empty 'Annotation ID gloss: English':

19HONDERD, ABORTUS-B, AFPAKKEN, AFSCHEIDEN, BEFFEN, BEGINNEN-C, BETRAPT, BIJVOORBEELD-C, BLOEIEN, BLOZEN, BOODSCHAPPEN-C, CI-E, CONCENTRATIE, EIKEL-A, FIETSEN-B, GEHOORAPPARAAT-C, GEHOORAPPARAAT-D, GOED-C, GRIJS-D, HANGEN, HANGERS, HART-C, HELPEN-C, HER-EN-DER, HOUVAST, IN-F, JOYSTICK, KINDERACHTIG, KLUNGELEN, KNOP, KOEL, KOMEN-E, KORT, LATER-D, LEUK-B, LUIDSPEAKER, MEEDOEN, MIMIEK-B, MIS-C, NEDERLAND-C, NIEUWtest, NIKS, NIKS-D, OF-B, OLIE-B, ONZICHTBAAR, OORDOP-B, OPVALLEN-B, OVERPLAATSEN, PECH-A, PECH-B, PECH-C, PLAATSEN, PLOTSELING-B, QUATSCH, RECHTSTREEKS, REMMEN-C, RINKELEN, RUIS, RUZIE-B, SCHAKELEN-B, SPORT-B, STERK-B, STOER, UIT-C, UITKNIJPEN, VERDOMME-C, VERDOMME-D, VERLIEFD-C, VERSCHIJNEN, VERSTAAN, VISUEEL-B, VOORBIJGAAN, VROUW-D, VROUW-E, WAT-E, WEGGOOIEN-B, WEGLOPEN, ZELFSTANDIG-B, ZITTEN-D, ZONDER, ZWAARD, ZWEEP

What shall I do with these cases?

**Comment by richardbank** [comment]
I'll have a go at it. Can't promise to have it finished by today, though. I'll comment here when I'm done.

**Comment by ocrasborn** [comment]
@richardbank Did you get around to completing this, or shall I have a go at it?

**Comment by richardbank** [comment]
Sorry, I forgot about this; I think I came halfway or so. Will look into it today.

**Comment by richardbank** [comment]
Finished the list, and re-checked. @Woseseltops : please check again if values are unique and not empty. New cases may have come up in the past 11 days.

**Comment by Woseseltops** [comment]
I checked, all double and empty cases are gone now :+1: .

I thought I could force in the database that annoation_id_gloss could only have unique values by settting unique=True, as I do here https://github.com/Signbank/NGT-signbank/commit/f1d958b8be5b860a15cf045f641dd25faa69ef07 , but I discovered by accident that this unique=True is only about the Django admin. 

This means the following for non-uniqueness in the following scenarios:
* Django admin, new gloss: not possible
* Django admin, modify existing gloss: not possible
* Signbank interface, new gloss: not possible
* Signbank interace, modify existing gloss: POSSIBLE

Do we want to integrate a check when modifying existing glosses? Because it could be quite a lot of work for a situation that rarely happens.

**Comment by Woseseltops** [comment]
Forget about all of the above; now that I did a database migration, you DO get an error in the 'Signbank interface, modifying existing gloss' situation.

**Comment by ocrasborn** [comment]
So... that means this can be closed, @Woseseltops ?

**Comment by Woseseltops** [comment]
Depends on whether you want fixed that changing an annotation id gloss to an existing (non-unique) annotation idgloss leads to a popup with an error message ;)

**Comment by Woseseltops** [comment]
@richardbank told me the message above is unclear, and also came up with a brilliant solution. I explain them both here:

The current situation (explanation of my previous comment):
1. You change the annotation id gloss to something that exists already (non-unique)
2. The website sends the change to a script called update.py
3. update.py crashes, because the new value is non-unique, which is mandatory
4. update.py sends back its error message
5. The website recognizes the response is an error message, and displays this in a popup

The brilliant solution by Richard: at step 4, recognize that is an error related to Uniqueness, and display a user friendly explanation along the lines of 'this id gloss already exists'.

**Comment by ocrasborn** [comment]
OK, let's do that.

**Comment by Woseseltops** [comment]
Done, and made the error message translatable as well.

**Comment by ocrasborn** [comment]
:-)

**Comment by richardbank** [comment]
Turns out the field 'ID gloss' should be unique as well. Please fix.

**Comment by Woseseltops** [comment]
For clarity, we have:

* idgloss = models.CharField(_("ID Gloss"), unique=True, max_length=50,   
* annotation_idgloss = models.CharField(_("Annotation ID Gloss: Dutch"),     
* annotation_idgloss_en = models.CharField(_(

This issue initially was only above the lower two, @rbank requested to also have the first one unique. I did the following:

  * Checked in both databases to find any doubles (nothing)
  * Changed the models, and migrated both databases
  * Checked what happened when modifying idglosses into existing ones now that the database doesn't allow it anymore. Result: the nice error message described above.

Everybody happy?

**Comment by ocrasborn** [comment]
Me happy.
